mordred/utils/add_tz_irc.py

[irc logs] Script to add timezones to the timestamp

[irc logs] Script to add timezones to the timestamp

---

mordred/bin/mordred.sh

[mordred] Indentation bug fixed

---

mordred/bin/mordred.sh

[mordred] Path to projectinfo.py as parameter.

[mordred] Path to projectinfo.py as parameter

---

mordred/bin/mordred.sh

Support for gmane added to mordred.

[mordred] Added support for gmane

---

mordred/bin/mordred.sh

Support for pipermail added to mordred.

[mordred] Added support for pipermail

---

mordred/bin/mordred.sh

[mordred] Added support for twitter

---

mordred/bin/mordred.sh

There was an empty "if statement" that it was causing an error during
the execution.

[mordred] Fixed issue with twitter empty if

---

mordred/utils/es_datafreshness.py

Have to include the complete path in the es in the conf file

[mordred] es_datafreshness.py version 0.2

---

mordred/bin/mordred.sh

Added support for stack exchange to mordred.

[mordred] Added support for stack exchange

---

mordred/utils/custom_kib.py

Script to manage tabs and panels

[mordred] Script to manage tabs and panels

---

mordred/bin/mordred.sh

[mordred] Added support for confluence

---

mordred/bin/mordred.sh

Support for jira added to mordred.

[mordred] Added support for jira

---

mordred/bin/mordred.sh

Updated the support for gerrit according to the
commit '5eb165ae65cd3dd685cd3e650411a119446b253d'
of perceval.

[mordred] Updated the support for gerrit

---

mordred/utils/custom_kib/tabs.py

This change avoids weird behaviours adding tabs.

[custom_kib.py] Fixed minor issue in adding tabs

---

mordred/bin/mordred.sh

[mordred] Add Mediawiki support

---

mordred/utils/custom_kib/tabs.py

Fixed bug adding tabs for the first time

[custom_kib.py] Fixed bug adding tabs for the first time

---

mordred/utils/custom_kib/requirements.txt

[custom_kib] Add requirements file

---

mordred/utils/json/eclipse2bitergia.py

Add script to generate the two JSON files we use now both for projects hierarchy and project-repos definition.

[mordred] Add script to generate new JSON format files for project

---

mordred/bin/mordred.sh

Now JIRA retrieval can be done by project adding it in the JSON file.
It strips the project from the URL, as well as the base url, so for example having the following URL:
`https://jira.fiware.org/browse/FIL`
It will strip the base url: `https://jira.fiware.org` and the project `FIL` for p2o to launch it.

[mordred] Add project support for JIRA's backend

---

mordred/bin/mordred.sh

There were an issue while launching p2o, the supybots elements were not being parsed correctly making the tool fail

[mordred] Fix supybot parsing for launching p2o

---

grimoire/arthur.py

In order to create different log files when executing Mordred, we need to allow submodules to be automatically set up using the following call:
```
getLogger(__name__)
```
These changes add this feature.

[logging] Add modular logging support to arthur.py

---

grimoire/arthur.py
grimoire/elk/enrich.py
grimoire/utils.py
utils/p2o.py

Add a new feature to refresh only the documents tagget with the
author_id passed via command line with option "--author_id"

[refresh] New option to refresh only a selected author_id

---

setup.py

Newer perceval (0.9.0).
Newer perceval-mozilla (0.1.1)
perceval-opnfv

Add updated dependencies.

---

grimoire_elk/_version.py
setup.py

New version for pypi, including new versions for dependencies.

[version] New version for pypi

---

kidash/setup.py

panels is actually grimoirelab-panels.

[kidash][setup] Fix dependency on panels package

---

README.md
grimoire_elk/elk/database.py
grimoire_elk/elk/enrich.py
setup.py

Add some parameters to setup.py, including extras_require (for sortinghat and arthur), and fix minor issue with generation of README.rst.
Closes #101.

[setup] Improve setup.py

---

grimoire_elk/panels.py
kidash/kidash.py

[kidash] Add option to clean all items not included in data sources provided
There are panels like overview or data status that include all data
sources in them. But for a specific dashboard, only the active data sources
should be included. This is a first version that needs to be checked for
layout issues yet.

[kidash] Add option to clean all items not included in data sources provided

---

utils/index_mapping.py

Improvements to index_mapping tool:
* Read and write Elasticsearches could be in different hosts
* Can use search-after for scrolling the index (alpha)
* Use sync bulk upload to check that all items are written

Index mapping ++

---

.travis.yml

The tests checks:
* Code style with flake8
* Integration tests

[travis] Add Travis config file for testing before merging commits

---

grimoire_elk/panels.py

It is not needed anymore to use files to list, import and export
dashboards. There are new methods to get the JSON dict directly.

[panels] Change the API so dashboards can be listed, imported and exported with a JSON in memory

---

grimoire_elk/arthur.py

Add code so that when refresh_identities is called with Null as a parameter for the filter (or with no parameter for filter), all items in the index are refreshed.

[enriched] Ensure that we have a method for refreshing whole indexes

---

grimoire_elk/arthur.py

A print command was included for tracing. This is just to remove it.

[enriched] Fix stale print command.

---

grimoire_elk/elk/enrich.py

This patch enables the ElasticSearch component to handle storage exceptions when uploading enriched data.

[enrich] Track storage exceptions when uploading enriched data to ES

---

grimoire_elk/elk/askbot.py

[elk] Update enrich_items method of Askbot for new tests

---

grimoire_elk/elk/meetup.py

[elk] Update enrich_items method of Meetup for new tests

---

grimoire_elk/elk/kitsune.py

[elk] Update enrich_items method of Kitsune for new tests

---

grimoire_elk/ocean/gitlab.py

This code includes the ocean backend for GitLab

[ocean] Add GitLab backend

---

grimoire_elk/ocean/puppetforge.py

This code includes the ocean backend for PuppetForge

[ocean] Add PuppetForge backend

---

grimoire_elk/ocean/launchpad.py

This code includes the ocean backend for Launchpad

[ocean] Add Launchpad backend

---

grimoire_elk/elk/git.py
grimoire_elk/ocean/git.py

This patch removes mappings for ES 2.x

[ocean] Remove ES 2.x mappings to index Git data

---

grimoire_elk/arthur.py
grimoire_elk/elk/enrich.py
grimoire_elk/ocean/elastic.py

This PR targets issues #224 and #222. It enables the use of the archive in GElk. Note that (currently) only storing data to archive is supported (it does not allow to fetch data from archives).

[archive] Allow handling archive

---

grimoire_elk/elk/git.py

Readded the logic to find refresh authors commits which new commits since the
last execution of the demography in order to update the author_max_date for them.

[enrich][git] Fix incremental demography update for already existing authors

---

grimoire_elk/arthur.py

This code allows to fetch data from a **single** archive

[archive] Add support to fetch data from archives

---

grimoire_elk/elastic.py
grimoire_elk/elk/askbot.py
grimoire_elk/elk/dockerhub.py
grimoire_elk/elk/enrich.py
grimoire_elk/elk/git.py
grimoire_elk/elk/github.py
grimoire_elk/elk/kitsune.py
grimoire_elk/elk/mbox.py
grimoire_elk/elk/mediawiki.py
grimoire_elk/elk/mozillaclub.py
grimoire_elk/elk/stackexchange.py
grimoire_elk/utils.py
tests/test_elk_elsticsearch.py
utils/gelk.py
utils/gh2arthur.py
utils/index_mapping.py
utils/ocean.py
utils/p2o.py
utils/track_items
utils/twitter2es.py

This PR enables to store enriched items using the common method safe_put_bulk. Thus, controlling possible failures and returning the number of inserted items

[elastic] Refactor how items are stored in ES

---

grimoire_elk/elk/askbot.py
grimoire_elk/elk/bugzilla.py
grimoire_elk/elk/discourse.py
grimoire_elk/elk/functest.py
grimoire_elk/elk/gerrit.py
grimoire_elk/elk/mediawiki.py
grimoire_elk/elk/mozillaclub.py
grimoire_elk/elk/redmine.py
grimoire_elk/ocean/askbot.py
grimoire_elk/ocean/bugzilla.py
grimoire_elk/ocean/confluence.py
grimoire_elk/ocean/discourse.py
grimoire_elk/ocean/gerrit.py
grimoire_elk/ocean/mediawiki.py
grimoire_elk/ocean/redmine.py

This patch temporally reverts mappings for a small subset of data sources to allow the correct creation of the corresponding dashboards.

[mappings] Temporally revert mappings

---

grimoire_elk/elk/bugzillarest.py
grimoire_elk/elk/git.py

This code fixes flake8 errors in git and bugzillarest elk backends

[elk] Fix flake8 errors for git and bugzillarest backends

---

grimoire_elk/elk/askbot.py

This code adds to the enriched item information about: (i) whether a question has an accepted answer,
(ii) the id of the accepted answer

[askbot] Refine information to track accepted answers

---

grimoire_elk/ocean/askbot.py
grimoire_elk/ocean/bugzillarest.py
grimoire_elk/ocean/discourse.py
grimoire_elk/ocean/dockerhub.py
grimoire_elk/ocean/gerrit.py
grimoire_elk/ocean/github.py
grimoire_elk/ocean/redmine.py
grimoire_elk/ocean/remo.py
grimoire_elk/ocean/stackexchange.py

This patch includes ElasticSearch 5.1.x mappings for several ocean backends

[ocean] Add ES 5.1.x mappings for ocean backends

---

grimoire_elk/elk/git.py

If areas of code output index does not exist and incremental mode
is enabled, then the index is created.
Notice that index names have been modified to follow a similar convention as onion study. Once #261 gets accepted, I will update documentation for this study to the MD file created in that PR.

[elk] Create areas of code output index if needed

---

grimoire_elk/ocean/askbot.py

This code enables ES 2.x mappings for the askbot backend.

[ocean] Add ES 2.x mappings for askbot backend

---

grimoire_elk/elk/discourse.py

This code enables mappings for the enrichment phase of the discouse backend.

[elk] Include mappings to discourse backend

---

grimoire_elk/enriched/askbot.py

This PR targets issue #275. Thus the proposed code includes a new attribute in the enriched item, used to track the status of answers of a given question.

[enrich] Add `answer_status` field to askbot

---

schema/askbot.csv

This patch adds a new keyword field in the askbot.csv, which gives insights about the status of answers (i.e., accepted or not_accepted).

[schema] Update askbot.csv

---

grimoire_elk/utils.py
utils/p2o.py

This PR removes flake8 errors, which are causing the tests to fail.

Fix flake8

---

grimoire_elk/enriched/git.py

fixes #318 in grimoirelab-perceval

Added support for co-author

---

grimoire_elk/enriched/enrich.py

The project fields that are added to the enriched items when there is
project information now includes also the meta fields if they exits.

[enrich][metadata] Add project metadata fields to the enriched items

---

tests/test_load_identities.py

This code includes a test to measure the time used to retrieve and store identities in sortinghat via elk. This test can be useful to measure and improve the performance of elk/sortinghat when loading identities.

[tests] Add test for load identities in sortinghat

---

grimoire_elk/enriched/git.py
grimoire_elk/enriched/github.py
grimoire_elk/enriched/jira.py
grimoire_elk/enriched/mbox.py
schema/github_issues.csv
schema/jira.csv
schema/mbox.csv

Emails were detected in git, github, jira and mbox. This commit
removes all the fields including emails.

[enrich] Remove emails from all enriched indexes

---

grimoire_elk/enriched/discourse.py

This code adds to the enriched item information about:
(i) whether a question has an accepted answer,
(ii) the id of the accepted answer.

[discourse] Add information to track accepted answers

---

grimoire_elk/enriched/twitter.py

This code changes the date value used to index tweets. Tweets come from logstash and the API, both include a @timestamp attribute, which is now used to index them.

[twitter] Change date value to index tweets

---

grimoire_elk/elk.py
grimoire_elk/enriched/enrich.py
grimoire_elk/enriched/git.py

This code allows to propagate the params defined in the mordred configuration files to elk. Depending on the study, elk now is able to set up the parameters for the study. The studies that benefit of this patch are onion, areas of code and demography.

[elk] Propagate study params from mordred to elk

---

grimoire_elk/enriched/twitter.py

This code changes the field_date to index twitter data from `@timestamp` to `created_at`

[twitter] Set field_date for twitter enricher

---

grimoire_elk/enriched/stackexchange.py

This code allows to deal with deleted users in stackoverflow questions, logging a warning to notify platform operator.

[enrich] Handle deleted user in stackoverflow

---

grimoire_elk/raw/jenkins.py

This code updates the mappings for Jenkins to make them compatible with versions of ES greater or equal to 5.x.

[raw] Update mappings for jenkins to ES 5.x

---

grimoire_elk/enriched/redmine.py

`assigned_to` fields are included after processing the
corresponding identity in SortingHat.

[enrich][redmine] Add `assigned_to` fields

---

grimoire_elk/enriched/enrich.py
grimoire_elk/enriched/sortinghat_gelk.py

This code replaces the exception WrappedValueError with InvalidValueError, recently introduced.

Align ELK with changes in SortingHat

---

grimoire_elk/enriched/twitter.py
grimoire_elk/raw/twitter.py
grimoire_elk/utils.py
tests/data/twitter.json
tests/test_twitter.py

This PR allows to handle Twitter data through the Perceval backend, decommissioning the use of log stash and the ad-hoc scripts `twitter_search` and `twitter2es`. This PR should be reviewed with the corresponding on Perceval https://github.com/chaoss/grimoirelab-perceval/pull/392

[twitter] Replacing logic to handle Perceval data

---

grimoire_elk/enriched/enrich.py

Some changes in SH API has broken how gelk finds the uuid for an identity.
This commit fixes it and use the new low level API from SH making the
logic simpler.

[enrich] Fix the logic for finding the uuid for a SH identity

---

grimoire_elk/raw/mattermost.py

This code parses the parameters for the mattermost perceval backend, thus enabling the execution of this backend in ELK.

[raw] Add parser params for perceval mattermost backend

---

grimoire_elk/enriched/git.py
grimoire_elk/enriched/mbox.py
tests/base.py
tests/test_git.py
tests/test_mbox.py

This PR includes tests for onion and demography studies in Git and kafka kip in Mbox enrichers

[tests] Add tests for studies

---

grimoire_elk/elk.py
grimoire_elk/utils.py
utils/p2o.py

WIth this PR p2o can be used another time to start studies in enriched indexes.

[p2o] Add support for execution a list of studies

---

grimoire_elk/enriched/ceres_base.py
grimoire_elk/enriched/git.py

This code replaces the import of grimoirelab toolkit to make the code working with the new package structure of the toolkit.
This PR is related to https://github.com/chaoss/grimoirelab-toolkit/pull/13

[enriched] Change toolkit import

---

grimoire_elk/raw/twitter.py

This code modifies the mapping of the raw items coming from Twitter, according to the perceval format.

[raw] Fix mapping Twitter

---

grimoire_elk/enriched/gitlab.py
grimoire_elk/raw/gitlab.py
grimoire_elk/utils.py
tests/data/projects-release.json
tests/test_gitlab.py

This PR proposes a raw and enrich connectors to allow GrimoireLab to handle GitLab issues.

[connectors] Add GitLab support

---

README.md

This code includes travis badge for to ease the understanding of build information.

[README.md] Fix travis badge

---

.travis.yml

Since no coverage information is shown, this PR attempts to fix the travis.yml.

[travis] Fix coverage execution

---

grimoire_elk/enriched/groupsio.py
grimoire_elk/raw/groupsio.py
grimoire_elk/utils.py
tests/data/groupsio.json
tests/data/projects-release.json
tests/test_groupsio.py

This PR proposes a raw and enrich connectors to allow GrimoireLab to handle mbox archives available through GroupsIO platform.

[connectors] Add GroupsIO support

---

tests/test_git.py
tests/test_mattermost.py
tests/test_slack.py

This code allows to run the tests against an ES which is not in a local machine. This modification applies also to ESs running in a docker image.

[tests] Enable tests from no-localhost ES

---

grimoire_elk/enriched/meetup.py

This code refactors the code of `get_rich_item_rsvps` and `get_rich_item_comment` in order to avoid false positive logs about missing rich rsvps and comments.

[enrich-meetup] Refactor code for get_rich_item_(rsvps,comment)

---

grimoire_elk/raw/elastic.py

This code improves the logging message in method `feed_items`. Thus, the term `ocean` is replaced with the name of the index where the items are inserted.

[raw] Improve logging message in elastic

---

grimoire_elk/enriched/git.py

Patch to add a try..except block to catch connection exceptions when getting commits during the demography study.

[demography] Catch conn exceptions when fetching author commits

---

grimoire_elk/enriched/gerrit.py

[enrich-gerrit] Replace list with yield

---

grimoire_elk/enriched/github.py

[enrich-github] Replace list with yield

---

grimoire_elk/enriched/git.py

[enrich-git] Replace list with yield

---

grimoire_elk/enriched/twitter.py

[enrich-twitter] Replace list with yield

---

grimoire_elk/elk.py
grimoire_elk/enriched/jenkins.py
tests/data/jenkins.json
tests/test_jenkins.py

Jenkins enricher now supports a regular expression for node
name cleaning.

[jenkins] Add node name cleaning based on RE

---

grimoire_elk/enriched/telegram.py

[enrich-telegram] Replace list with yield

---

grimoire_elk/enriched/supybot.py

[enrich-supybot] Replace list with yield

---

grimoire_elk/enriched/slack.py

[enrich-slack] Replace list with yield

---

grimoire_elk/enriched/stackexchange.py

[enrich-stackexchange] Replace list with yield

---

grimoire_elk/enriched/remo.py

[enrich-remo] Replace list with yield

---

grimoire_elk/enriched/redmine.py

[enrich-redmine] Replace list with yield

---

grimoire_elk/enriched/puppetforge.py

[enrich-puppetforge] Replace list with yield

---

grimoire_elk/enriched/phabricator.py

[enrich-phabricator] Replace list with yield

---

grimoire_elk/enriched/mattermost.py

[enrich-mattermost] Replace list with yield

---

grimoire_elk/enriched/kitsune.py

[enrich-kitsune] Replace list with yield

---

grimoire_elk/enriched/jira.py

[enrich-jira] Replace list with yield

---

grimoire_elk/enriched/discourse.py

[enrich-discourse] Replace list with yield

---

grimoire_elk/enriched/confluence.py

[enrich-confluence] Replace list with yield

---

grimoire_elk/enriched/askbot.py

[enrich-askbot] Replace list with yield

---

grimoire_elk/elastic_items.py

This code refactors the `fetch` method, removing the infinite loop and break statements.

[elastic_items] Refactor `fetch` method

---

grimoire_elk/enriched/ceres_base.py
grimoire_elk/enriched/git.py
grimoire_elk/enriched/jira.py
grimoire_elk/enriched/mbox_study_kip.py
grimoire_elk/enriched/phabricator.py
grimoire_elk/raw/elastic.py
tests/model.py
tests/test_enrich.py
tests/test_gerrit.py
tests/test_git.py
tests/test_jenkins.py
utils/gh2arthur.py
utils/index_mapping.py

This code fixes flake8 errors in tests, utils, raw and enriched modules, which appeared after the latest release of the same package.

[ELK] Fix flake8 errors

---

grimoire_elk/enriched/meetup.py
tests/test_meetup.py

This code changes the logic to enrich items. Now, raw items are enriched on the fly together with enriched rsvps and comments. Tests have been modified accordingly.

[enrich-meetup] Refactor logic to enrich items

---

grimoire_elk/enriched/discourse.py
tests/test_discourse.py

This code changes the logic to enrich items. Now, raw items are enriched on the fly together with enriched comments. Tests have been modified accordingly.

[enrich-discourse] Refactor logic to enrich items

---

grimoire_elk/elastic_items.py

This codes handle attempts of fetching data from none indexes.

[elastic_items] Handle pagination over none index

---

grimoire_elk/enriched/askbot.py

This code changes the logic to enrich items. Now, raw items are enriched on the fly together with enriched answers and comments.

[enrich-askbot] Refactor logic to enrich items

---

grimoire_elk/raw/gitlab.py
tests/test_gitlab.py

This code allows to pass a list of blacklisted item ids (issues or pull requests) via the projects.json.

[raw-gitlab] Allow passing blacklisted items from projects.json

---

grimoire_elk/enriched/gerrit.py

This code converts the mapping of the status attribute to keyword.

[enrich-gerrit] Change mapping type of status attribute

---

grimoire_elk/enriched/github.py

This code converts the mapping of the state attribute to keyword.

[enrich-github] Change mapping type of state attribute

---

grimoire_elk/elk.py

This code refactors the method `refresh_identities` to be able to work with the recent changes in the sortinghat api. In a nutshell, in order to reduce the memory footprint, the sortinghat api
returns a generator of identities (instead of lists), the `refresh_identities` method manipulates this list to prepare a filter used to update the data with the identities information updated.

[elk] Refactor `refresh_identities`

---

grimoire_elk/enriched/enrich.py

This code replaces the use of dateutil parser with the methods provided by the grimoirelab-toolkit. Thus, promoting homogeneity in the code and reducing the risk of failures.

[enrich] Use grimoirelab-toolkit methods

---

grimoire_elk/enriched/ceres_base.py
grimoire_elk/enriched/enrich.py
grimoire_elk/enriched/git.py
grimoire_elk/enriched/study_ceres_aoc.py
grimoire_elk/enriched/study_ceres_onion.py
setup.cfg

Log lines now include more info about the specific study,
data source or index in order to ease finding them among
other log lines.

[studies] Improve log lines prefix (rebased)

---

schema/gitlab_issues.csv
schema/gitlab_merges.csv

Add `aggregatable` and `description` fields to GitLab CSVs.

[schemas] Fix GitLab CSVs to add missing columns

---

grimoire_elk/elk.py
grimoire_elk/enriched/sortinghat_gelk.py

This code includes the stacktrace information in the log messages generated when exceptions are thrown during the collection, enrichment of the data as well  during the loading of identities.

[ELK] Include stacktrace in log messages

---

grimoire_elk/elastic.py

This code changes the log message level from INFO to DEBUG when inserting data to ElasticSearch.

[elastic] Change log message level when inserting data to ES

---

grimoire_elk/enriched/ceres_base.py
grimoire_elk/enriched/git.py
grimoire_elk/enriched/mappings/git_aoc.json
grimoire_elk/enriched/study_ceres_aoc.py
grimoire_elk/enriched/study_ceres_onion.py

These changes make the study enrich only those repos included
in `projects.json` file instead of enriching the whole set
of data found in the input index.

[studies] Add origin based enrichment in AOC

---

grimoire_elk/enriched/git.py
schema/git.csv

Reverts chaoss/grimoirelab-elk#559

Revert "[enrich] Update Git references data in raw and enriched indexes"

---

grimoire_elk/elastic.py
grimoire_elk/elk.py
grimoire_elk/enriched/enrich.py
grimoire_elk/enriched/git.py
grimoire_elk/utils.py

This PR includes the method to delete items from the raw, enriched and studies indexes before a given date. This change is needed to define retention policy data.

[elastic] Add method `delete_items`

---

grimoire_elk/enriched/utils.py

This code changes the way how the last enrich date is calculated. If the enriched index is empty the last enrich date is set to None. Otherwise, the last enrich date is the minimum between the last metadata_timestamp of the enriched index before starting the TaskEnrich (this covers the case of repos with filter-raw) and the last metadata_timestamp of the items filtered by repo (this covers the case of a list of repos which data is shared in the same index).

[utils] Change assessment of last enrich date

---

grimoire_elk/enriched/git.py

This code fixes the ElasticSearch error `Too many dynamic script compilations` which occurs on the painless script used to add branch information. The script is modified to use the `params` attribute, that allows to compiles and stores the script in cache, thus avoiding compiling the script over and over.

[enriched] Fix `Too many dynamic script compilations` in git enrich

---

grimoire_elk/enriched/finosmeetings.py
tests/test_finosmeetings.py

This code includes the information about sortinghat identities in the enriched items for the finosmeetings data source. Furthermore it sets the project value to the value of `cm_program` present in the item.

[enriched] Enhance finosmeeting enriched items

---

grimoire_elk/enriched/finosmeetings.py
tests/test_finosmeetings.py

This code sets the project value to the cm_title, which was previously cm_program.

[finosmeetings] Change project value to cm_title

---

tests/data/finosmeetings.json

This code updates the finosmeetings test data, which now includes the `cm_type` info.

[tests] Update finosmeetings test data

---

grimoire_elk/enriched/gerrit.py

This code replaces datetime, time and dateutil.parser calls to equivalent calls of grimoirelab-toolkit, thus reducing possible point of failures due to duplicate code.

[enriched-gerrit] Use grimoirelab-toolkit calls

---

grimoire_elk/enriched/jira.py
tests/data/jira.json
tests/test_jira.py

This code includes Jira comments to the enriched index. To do this, changes have been made to allow the cohesistance of both comments and issues in the same index, following an approach similar to meetup and stackexchange enrichers. Thus, enriched issues and commits have different ids, the former is the issue
ids, while the latter is a str concatenating the issue id and the comment id.

[enriched-jira] Add comments to enriched index

---

grimoire_elk/enriched/git.py

This PR defines a study to process git branches. It consists in updating the branch information for each
doc (which represents a git commit) in the enriched index.
The study accesses the projects.json, retrieves the urls of git repos and iterates them one by one to update branch info within the documents. The study is activated by adding the section [enrich_git_branches] in the setup.cfg. This section doesn't require any parameter.

[enriched-git] Add study to process git branches

---

grimoire_elk/enriched/git.py

This code includes some log messages to help operators following/understanding the execution of the study.

[enriched-git] Add log info to enrich_git_branches

---

grimoire_elk/raw/slack.py
tests/data/slack.json

This code handles `illegal_argument_exception` errors on the field `data.blocks.elements.text` which prevent the insertion of slack items. Tests data has beeen changed accordingly.

[raw-slack] Fix illegal_argument_exception for data.blocks.elements.text

---

grimoire_elk/elk.py

This PR modifies the `feed_backend` method to return an error msg. This information is then consumed by Mordred.

[elk] Return error msg from `feed_backend`

---

grimoire_elk/enriched/github.py

This code sets the variables roles to merged_by_data, user_data, assignee_data, thus allowing the refresh
of sortinghat information for the corresponding identities.

[enriched-github] Set roles to allow refresh identities

---

grimoire_elk/enriched/jira.py

This PR handles missing identity data in Jira items

[enriched-jira] Handle missing identity data

---

.travis.yml
requirements.txt
setup.py

This PR cleans the content of the travis.yml, requirements.txt and setup.py by avoiding installing packages which are installed by other GrimoireLab components. It also aligns the requirements.txt with the install_requires in the setup.py

Polish travis, requirements.txt and setup.py

---

grimoire_elk/enriched/enrich.py

This code allows to handle errors that may pop up during the execution of the demography study. The
update_by_query underlying the study is executed with the params `wait_for_completion=true` and
`conflicts=proceed`. The former waits that the updates have finished, while the latter prevents
to stop the study in case of a version conflicts in the documents updated. Furthermore, the request
issuing the update_by_query is wrapped in a try/except block to ignore Retry errors, which may occur when ElasticSearch is not available.

[enriched-enrich] Handle errors in demography study

---

tests/test_gerrit.py
tests/test_git.py

This code increase the waiting time to check that the demography study correctly set the corresponding
fields.

[tests] Increase waiting time for demography study

---

schema/jenkins.csv

This PR add the missing fields to Jenkins CSV schema.
Signed-off-by: Alberto Pérez García-Plaza <alpgarcia@bitergia.com>

[Jenkins] Update CSV schema for Jenkins

---

tests/test_load_identities.py

This PR allows to execute the tests for identities loading separately by adding the main method.

[tests] Add main to test_load_identities

---

grimoire_elk/enriched/study_ceres_onion.py

This code filters the authors marked as bot, thus removing noise from the onion analysis.

[enriched-onion] Filter bots from onion study

---

README.md

This code kickstarts the improvement of the ELK documentation. In this
iteration the idea is to summarize what ELK does and start listing the
different types of data handled.

[doc] Improve README.md info

---

README.md

Add minor changes to the README file in order to make both the description and the list of fields more easy to be read&understood.

Add minor changes to the README file.

---

grimoire_elk/elastic.py
grimoire_elk/elastic_items.py
grimoire_elk/elk.py
grimoire_elk/enriched/git.py
grimoire_elk/raw/elastic.py

This code aims at improving the log messages of ELK in order to reduce their size and make them more meaningful. Special attention has been given to incremental messages and empty repo error messages.

[elk] Improve logs elk

---

grimoire_elk/elk.py
grimoire_elk/enriched/ceres_base.py
grimoire_elk/enriched/enrich.py
grimoire_elk/enriched/git.py
grimoire_elk/enriched/study_ceres_aoc.py
grimoire_elk/enriched/study_ceres_onion.py
tests/test_gerrit.py
tests/test_git.py

This code improves log messages of studies to clean our logs and
make it more readable
Signed-off-by: Quan Zhou <zhquan7@gmail.com>

[studies] Improve log messages

---

grimoire_elk/enriched/enrich.py
grimoire_elk/enriched/git.py
grimoire_elk/enriched/github.py

This adds new study that enables enriching a given index with some extra fields. This can be very useful to enable users to further enhance/tag data with some extra info relevant to their organisations.
Added missing sign off

[Studies] Add new study to enable enriching a target index with extra fields

---

README.md
tests/test_git.py

This code adds a test for the new study `enrich_extra_data`, furthermore documentation
has been also included.

[tests] Add test for `enrich_extra_data`

---

grimoire_elk/elastic_items.py

[elastic_items] Fix message when scroll_size is 0

---

.travis.yml
grimoire_elk/elastic.py
grimoire_elk/elastic_items.py
grimoire_elk/enriched/ceres_base.py
grimoire_elk/enriched/dockerhub.py
grimoire_elk/enriched/enrich.py
grimoire_elk/enriched/git.py
grimoire_elk/enriched/kitsune.py
grimoire_elk/enriched/mappings/git_aoc_es7.json
grimoire_elk/enriched/mappings/onion_es7.json
grimoire_elk/enriched/mbox.py
grimoire_elk/enriched/mediawiki.py
grimoire_elk/enriched/mozillaclub.py
grimoire_elk/enriched/study_ceres_aoc.py
grimoire_elk/enriched/study_ceres_onion.py

This code provides some fixes to support ODFE 1.2.0/elasticsearch 7.2.0.
This PR should be reviewed together with https://github.com/chaoss/grimoirelab-sirmordred/pull/362

[ELK] Support ODFE

---

grimoire_elk/enriched/git.py

This code allows to handle the Perceval RepositoryErrors triggered when the repository isn't found locally. The exception is caught and a warning message is logged.

[enriched-git] Handle missing local git repo

---

grimoire_elk/elastic_items.py
tests/test_elastic_items.py

This code includes a battery of new tests for the class ElasticItems. This change is needed to
increase the test coverage of sensible parts of GrimoireELK. Furthermore docstrings have been
add for all methods.

[elastic_items] Improve doc and test coverage

---

tests/test_elastic_items.py

[tests] Fix CI tests for elastic items

---

grimoire_elk/elastic.py

This code allows to load aliases containing filters, which at the moment are manually loaded.

[elastic] Enable loading of complex aliases

---

grimoire_elk/enriched/telegram.py
tests/data/telegram.json
tests/test_telegram.py

This PR addresses part of https://github.com/chaoss/grimoirelab-elk/issues/779, thus it handles Telegram messages without an username.

[enriched-telegram] Handle missing username in Telegram messages

---

README.md

Added some instruction for secure elasticsearch and docker users.

[doc] Update readme for secure elasticsearch

---

tests/test_git.py

Test Method for Area of Code has been added in test_git.py file.
The main reason for doing so was to increase the coverage of git.py file. Which has been increased from 44% to 49% by adding this test.
Signed-off-by: Kshitij Gupta <kgupta3199@gmail.com>

Added test method for Area of Code in test_git.py

---

grimoire_elk/enriched/askbot.py
grimoire_elk/enriched/bugzilla.py
grimoire_elk/enriched/bugzillarest.py
grimoire_elk/enriched/confluence.py
grimoire_elk/enriched/crates.py
grimoire_elk/enriched/finosmeetings.py
grimoire_elk/enriched/gerrit.py
grimoire_elk/enriched/git.py
grimoire_elk/enriched/github.py
grimoire_elk/enriched/github2.py
grimoire_elk/enriched/gitlab.py
grimoire_elk/enriched/jira.py
grimoire_elk/enriched/kitsune.py
grimoire_elk/enriched/mattermost.py
grimoire_elk/enriched/mbox.py
grimoire_elk/enriched/mediawiki.py
grimoire_elk/enriched/meetup.py
grimoire_elk/enriched/phabricator.py
grimoire_elk/enriched/puppetforge.py
grimoire_elk/enriched/remo.py
grimoire_elk/enriched/rss.py
grimoire_elk/enriched/slack.py
grimoire_elk/enriched/stackexchange.py
grimoire_elk/enriched/supybot.py
grimoire_elk/enriched/telegram.py
grimoire_elk/enriched/twitter.py

This code avoid the error
`TypeError: argument of type 'NoneType' is not iterable`.

[enriched] Check first if the instance of `item` is dict

---

tests/base.py
tests/data/git.json
tests/test_git.py

Added tests for `pair_programming` in Git backend to increase coverage
Signed-off-by: Nitish Gupta <imnitish.ng@gmail.com>

added test for pair_programming in Git backend

---

grimoire_elk/enriched/git.py

This PR adds docstring for `pair_programming` enabled mode in Git backend based on the discussions [here](https://github.com/chaoss/grimoirelab-elk/issues/825)
Fixes #825 
Signed-off-by: Nitish Gupta <imnitish.ng@gmail.com>

updated docstring for pair_programming

---

grimoire_elk/enriched/git.py

This code allows to handle connection problems when accessing the repo to update the git branches.

[enriched-git] Handle connection problems during enrich_git_branches

---

grimoire_elk/enriched/git.py

This code add a new param `run_month_days` to declare the days of
the month to run the study `enrich_git_branches`.

[enrich-git] Add the param `run_month_days` to enrich_git_branches

---

releases/unreleased/store-and-process-github-events.yml

This code includes the release note for the feature #853

[releases] Add release note for feature #853

---

poetry.lock
pyproject.toml

This code adds support for poetry, thus the poetry.lock and pyproject.toml are
committed to the repository.
The pyproject.toml has been derived from https://github.com/chaoss/grimoirelab-elk/blob/master/requirements.txt

[ELK] Add poetry support

---

tests/data/telegram.json
tests/test_telegram.py

This commit adds more entries to test data
of telegram to improve the test coverage.
Signed-off-by: Animesh Kumar <animuz111@gmail.com>

[telegram] Improve test coverage

---

pyproject.toml

Fix for [#907](https://github.com/chaoss/grimoirelab-elk/issues/907)

Fix Geopy dependency error

---

grimoire_elk/enriched/phabricator.py

Fixed:
- `time_to_close_days`: time from ticket creation to ticket close
(resolved, wontfix, invalid, spite, duplicate)
Added:
- `closed_at`: date the ticket was closed
Removed:
- `time_open_days_enrich`
- `timeopen_days`

[enriched/phabricator] Fix the field `time_to_close_days`

---

grimoire_elk/enriched/jira.py

Fix for  https://github.com/chaoss/grimoirelab-elk/issues/931

[JIRA] Fix for p2o enrich data fails when jira user is anonymous

---

grimoire_elk/enriched/discourse.py

This code fixes the error of a private instance. When the
Enricher tries to collect category information, the credentials
are required in the requests.

[enrich/discourse] Add credentials to collect category info

---

grimoire_elk/raw/slack.py

This code allows to handle the fields in `data.files` to
avoid the error `Failed to insert data to ES`

[raw/slack] Handle fields in 'data.files'

---

grimoire_elk/enriched/slack.py
grimoire_elk/raw/slack.py

This code allows enriching items without user data.

[enriched/slack] Fix enrich items without user data

---

grimoire_elk/enriched/cocom.py

use hashlib instead hash() to create a uniq id

---

schema/twitter.csv

The aggregatable column for the field `place.bounding_box.coordinates` needs to be set to true.
Signed-off-by: Rashmi K A <k.a.rashmi04@gmail.com>

[schema] Fix twitter schema

---

tests/data/telegram.json
tests/test_telegram.py

Coverage was missing for line 133-134.
This commit fixes that.
Signed-off-by: sevagenv <sevagenv@gmail.com>

[tests/data] Improve telegram coverage

---

grimoire_elk/enriched/github.py

Perceval return this dict when the user is no longer exist or the
token doesn't have permission.
```
{"organizations": []}
```
User parameters are set to 'None' on this change.

[enriched/github] Fix KeyError when getting user info

---

grimoire_elk/enriched/github2.py

This code fixes when the PR or issue is assigned to an unavailable
user.

[enriched/github2] Fix KeyError 'login'

---

grimoire_elk/raw/mattermost.py
tests/test_mattermost.py

With the addition of https://github.com/chaoss/grimoirelab-perceval/pull/748 to grimoirelab-perceval, it is now possible to call perceval using mattermost team & channel names.  This means that it is possible to accept a standard mattermost URL in grimoirelab-elk.  This PR adds support for this ability, while maintaining support for "legacy" repos in the old format.
This also adds a degree of validation to URLs, since they are now matched by regex, and improperly formatted URLs will fail to match.  I think this could be an opportunity to add an informative error message linking to the docs, but I wasn't able to find a place where the URL format is documented to link to.
[`mattermost.py:125`][] has an unfilled (TODO) where I think it would be good to link documentation.  I'd be happy to …

[mattermost] Allow parsing standard mattermost urls

---

doc/studies.md

1. Fixes #1045 by updating URL `Mordred config documentation` in `studies.md` to link discussed in issue

 Fixes #1045 update Mordred config doc link

---

AUTHORS
releases/unreleased/Use_entry_points_to_support_plugin_mechanism.yml
releases/unreleased/[enriched]-the-names-of-the-study-aliases-are-now-configurable.yml
releases/unreleased/[slack]-handle-fields-in-data.file.yml

This PR restores the changelog entries removed from the release candidate and changes the author's format of one of the entries.

Restore changelog entries from release candidate

---

poetry.lock
pyproject.toml
releases/unreleased/new-pandas-version.yml

Update the version of Pandas to the newest version compatible with Python 3.7+.

Update Pandas version to ^1.3.5

---

grimoire_elk/elastic_items.py
grimoire_elk/elk.py
grimoire_elk/raw/elastic.py
releases/unreleased/option-to-date.yml

This code allows fetching data until a specific date by activating `to-date`.

Add 'to-date' option on the backend sections

---

grimoire_elk/elk.py
grimoire_elk/enriched/sortinghat_gelk.py
releases/unreleased/load-identities-performance.yml

This PR improves the performance of load identities. process by 30-40%. Instead of inserting the identities one by one, now inserts the identities in batches of 100, reducing the number of queries to SortingHat.

Improve load identities process performance

---

doc/studies.md

Signed-off-by: kaxada <ekaxada@gmail.com>

fixed doc typos

---

releases/unreleased/first-major-release.yml

We are happy to announce we are ready to release GrimoireLab 1.0

Prepare for major release

---

grimoire_elk/enriched/bugzilla.py
grimoire_elk/enriched/bugzillarest.py
releases/unreleased/keywords-data-on-enriched-items.yml
schema/bugzilla.csv
tests/data/bugzilla.json
tests/test_bugzilla.py
tests/test_bugzillarest.py

This PR adds the keywords field to the enriched indices for the  bugzilla backends.

Add keywords for bugzilla backends

---

grimoire_elk/enriched/github.py
grimoire_elk/enriched/github2.py
releases/unreleased/github-user-keyerror-in-enriched-index.yml

Fix the rest of the fields of an AI user to correct `KeyError`:
- email
- company
- location

[enriched/github] Fix KeyError
