mordred/bin/mordred.sh
There is a bug with the argument "--from date" in mordred.sh.
When p2o.py is called from mordred.sh using a single variable for the
value "--from-date" and the date value (e.g.: "--from-date 2016-01-01"),
that value is interpreted wrongly by python. Python sees the value of the
variable as an unique parameter instead of two of them.
I've split the value of the variable in two parts, the string "--from-date"
and the date value.
=> [mordred] Bug with argument --from-date fixed

mordred/bin/mordred.sh
Data collection for stack exchange wasn't supporting the field "--from-date". Fixed.
Function "jecnkins_enrichment" was writing its logs into bugzilla-enrichment.log. Fixed.
=> [mordred] Minor issues fixed

grimoire/elk/jira.py
The following dictionaries are now handled when they are None:
creator, priority and reporter. All of them part of issue["fields"]
=> [enrich][jira] Fix TypeError bugs checking if issue fields are None

mordred/bin/mordred.sh
In 6c3c6d4fedc19cacb366f103b2f78e8e4796798f I've introduced support for JIRA projects, but with that approach I broke the existing one of fetching the whole JIRA website. Before, there was a variable in mordred checking the website, now it should be added in the JSON file like other data sources.
BTW I already did test it in pre-pro environment
=> [mordred] Add support for fetching the whole JIRA website

grimoire/_version.py, setup.py
This files are the first step to support installation via pip.
For now, they work only with grimoire module.
This means the grimoire module can already be installed by running
python3 setup.py install
=> Add files for automatic installation.

grimoire_elk/_version.py, setup.py
This includes a change to grimoire_elk/_version.py to push it up to 0.22, and a dependency on Perceval, specifying at least 0.5.
=> Minor modifications to produce pypi package 0.22

grimoire_elk/_version.py, setup.py
perceval-mozilla is needed fpr p2o to run. For now, I'm including
it as a dependency. Probably we should make grimoire_elk a bit
smarter, and use perceval-mozilla only if it is available, or
else, throw an exception if it is invoked when calling the module,
but it is not installed.
I bumped version to 0.22.1 to upload a new package to pypi.
=> Add dependency on perceval-mozilla

README_kidash.md, setup_kidash.py
Changes to allow kidash.py to be pckaged as a separate package.
This allows for easy installation of kidash.py, assuming
grimoire-elk is already installed (otherwise, it will be pulled
by dependencies in grimoire-kidash).
=> Add support for grimoire-kidash pip package.

grimoire_elk/elk/git.py
In general, we're using author_date for most info.
Maybe in a later release we should include both author_tz
and commit_tz, but for now, this little change do not require
changes in panels.
=> Change TZ so that it comes from author_date

grimoire_elk/ocean/gerrit.py
got error   `unsupported operand type(s) for +: 'int' and 'str'` on gerrit ocean. fixed.
=> Fix string to integer concatenation error.

setup.py
The latest release of perceval-opnfv is 0.1.0, so we better have that as dependency, otherwise there is no package to satisfy it ;-)
=> Downgrade dependency on perceval-opnfv

grimoire_elk/elk/enrich.py
Version was obtained by getting the git commmit description,
using the git command. Instead of that, use the _version.py file
that we maintain for consistent versioning.
The previous schema, based on the git command,  does not work
with pip packages, since they are not clones of the git repo.
=> [enrich] Use _version.py to get GELK version.

grimoire_elk/_version.py, grimoire_elk/panels.py, kidash/README.md, kidash/_version.py, kidash/setup.py
Now, panels (JSON files with panel defintions) are looked for
first in a local directory panels/json, and if not found, in the
panels module, if it is present and importable.
For maintaining compatibility, panels with names such as
"panels/json/git.json" are supported. But the most simple
"git.json" is also supported, meaning "git.json" file in the
current directory, or "git.json" file in the corresponding
directory of the modules file.
See README.md for more details.
Versions for both grimoire-elk and grimoire-kidash are updated.
grimoirelab-panels is now a dependency of grimoire-kidash.
=> [kidash] Add support for using panels in the panels module

grimoire_elk/elk/jira.py
Story points in Jira are available when the project is created as an agile "Scrum" project, and "Story points" are ckecked in as a configuration option for the project ("Setup to use Story Points").
In this case, when the raw index is produced by Perceval, it includes stuff like:
```
"data": {
"key": "PTNFLY-2602",
...
"fields": {
...
"customfield_10005": {
"name": "Story Points",
"value": 3.0,
"id": "customfield_10005"
},
...
"changelog": {
"startAt": 0,
"total": 10,
"histories": [
...
{
"author": {
"items": [
{
"fieldtype": "custom",
"field": "Story Points",
"to": null,
"fieldId": "customfield_10005",
"from": null,
"toString": "3",
"fromString": null
}
]
```
We´re getting story points from the first occurrence of them, in the list of fields. The logic is simple: check in …
=> [jira] Add story points to enriched index, when they are available

grimoire_elk/elk/jira.py
When SCRUM is activated in Jira, the sprint name comes encoded in a weird field:
```
"customfield_10007": {
"name": "Sprint",
"value": [
"com.atlassian.greenhopper.service.sprint.Sprint@5de0588[id=230,rapidViewId=4,state=ACTIVE,name=PatternFly Sprint 49,goal=,startDate=2017-10-24T18:25:41.062Z,endDate=2017-11-07T02:14:00.000Z,completeDate=<null>,sequence=230]"
],
"id": "customfield_10007"
},
```
This code extracts from this value field it the contents between ",name="  and ",", which is assumed to be the name dof the sprint, and uses it to produce a new field in the enriched index (sprint).
=> [jira] Add code to enrich "sprint" name when SCRUM is activated.

grimoire_elk/elk/jira.py
The check we had when looking for sprints and story points failed in some cases. Improve it, so that it doesn't fail with other formats of custom fields.
=> [jira] Add better checks when looking for sprints and story points

grimoire_elk/elk/crates.py, grimoire_elk/ocean/crates.py
The perceval backend for crates does not need any repository param.
But we need to add an empty repository to projects.json so the backend
is executed by mordred. Before creating the real perceval backend we need
to remove this fake repository param:
Contents of projects.json:
{
"grimoirelab": {
"crates": [""]
...
=> Remove crates empy fake repository needed by mordred

grimoire_elk/ocean/phabricator.py
This fix the error:
[data.fields.priority.subpriority] cannot be changed from type [long] to [float]
A float field could handle also a long field.
=> [ocean][phabricator] Fix to float the subpriority field

grimoire_elk/elk/elastic.py
During the bulk upload in sync mode, items are now packed so after each pack, the number of items really indexed as new can be check in order to detect duplicate items or problems adding the items (for example for mappings issues).
=> Bulk sync packs improvements

grimoire_elk/elk/bugzilla.py, grimoire_elk/elk/bugzillarest.py
[enrich][bugzillarest] Change fields to use the same names than in bugzilla
In order to reuse the bugzilla panel also for bugzillarest panel
this commit add some fields and rename others:
* Added grimoire_creation_date
* Added assignee information from Sortinghat
* Rename summary to main_description
* Added timeopen_days
* Added changes field with the total number of changes for a bug
[enrich][bugzilla] Remove project_name field to avoid confussions with dashboard projects
=> Enrich bugzilla rest 4611

grimoire_elk/elk/meetup.py
If a meetup event does not include the date field, it is not processed.
In this case, the comments and rsvps events must not be generated.
=> [enrich][meetup] Don't create comments and rsvps events for empty meetup items

grimoire_elk/elk/enrich.py
There was a case in which the domain was not added to the identities
field during enrichment. This fix covers it.
=> [enrich][sortinghat] Add identity domain using the profile information

grimoire_elk/elk/elastic.py
With old indexes (twitter for example) the old mapping are not
compatible with the current ones, and this causes a problem.
Instead of raising an exception, which will stop the process, log
a warning about the issue.
=> [mappings] If a mapping can not be created just log the issue

grimoire_elk/arthur.py, grimoire_elk/elk/elastic.py
If the number of identities is higher than elastic.max_items_clause (1000)
then all the index is refreshed. The max number of clauses that Elasticsearch
support by default is 1024, so with this limit we won't have issues
executing the search query with all the identities to find their related
items.
=> [autorefresh] Limit the max number of identities to be searched for refreshing

kidash/MANIFEST.in, kidash/bin/kidash, kidash/grimoire_elk, kidash/kidash/__init__.py, kidash/kidash/_version.py, kidash/kidash/kidash.py, kidash/setup.py, utils/kidash.py
This commit unbundles kidash completely from grimoire-elk. Now, all of kidash lives in the kidash directory, and everything should be ready to relocate in a standalone repo.
The kidash.py binary is now kidash, in the bin directory. The pip package is now kidash. Version now is 0.4.0 (it was 0.30.x with GrimoireELK, but then it was grimoire-kidash, so this is really a new package).
Please, apply this one only when grimoirelab/mordred#59 is ready to go. Ideally, accept both simultaneously, so that Mordred still works after this change.
=> [kidash] Unbundle kidash completely

grimoire_elk/elk/git.py
Some queries to Elasticsearch needed ES 6.x headers.
=> [git] Add Elasticsearch 6.x support for study in git.

grimoire_elk/elastic_items.py
This query which works with ES < 6.x does not work anymore:
```
{
"query": {
"bool": {
"must": [
{},
{
"terms": {
"author_uuid": [
"5d9fea1ff2d686c25497d2b8010e6f9ddbb8f2a4",
"dae602936b2ccd72b8a62b7a428a2b94e7042d84"
]
}
}
]
}
}
}
```
The inicial empty term "{}," must be removed.
=> [elastic_items] Remove empty intial filter because ES 6.x does not support it

grimoire_elk/ocean/confluence.py
This patch allows to filter out the indexing of the body content for confluence items. Thus, avoiding max_bytes_length_exceeded exceptions thrown by ElasticSearch when uploading data
=> [ocean/confluence] Filter out body.storage.value from index

grimoire_elk/elk/git.py
The key is that the new enriched commits are the ones that don't have
the demography study fields: author_min_date and author_max_date. So only
the authors of these new commits must be refreshed.
=> [enrich][git][demography] Fix the demography study logic so it works in incremental mode always

grimoire_elk/arthur.py, grimoire_elk/elk/git.py
Fix bug when refreshing identities in pair programming git.
The uuid in this case is not unique (a raw commit could create several enriched commits with the same uuid) so a new git_uuid has been added which is unique.
=> [git] Fix for refresh identities in pair programming git

grimoire_elk/elk/elastic.py, grimoire_elk/ocean/jenkins.py
This fix prevents to index the comment on a changeSet. Due to some large comments on changeSets, some Jenkins items caused ElasticSearch to fail in storing them.
=> [jenkins] Remove data.changeSet.items.comment from index

.travis.yml
This code introduces 15 second delay before the build script starts to let ElasticSearch starts. Thus it avoids the build to stall.
=> [travis] Add delay to make ES start

grimoire_elk/ocean/elastic.py
This patch adds warnings to the method _items_to_es within ocean/elastic.py. It is thrown when a mismatch exists between the number of json items in input and the number of the inserted ones in the ES storage
=> [ocean] Add warning when json items are not inserted to ES

grimoire_elk/elk/discourse.py
=> [elk] Update enrich_items method of Discourse for new tests

grimoire_elk/elk/dockerhub.py
=> [elk] Update enrich_items method of Dockerhub for new tests

grimoire_elk/elk/stackexchange.py
=> [elk] Update enrich_items method of Stackexchange for new tests

grimoire_elk/elk/mozillaclub.py
=> [elk] Update enrich_items method of MozillaClub for new tests

grimoire_elk/elk/mediawiki.py
=> [elk] Update enrich_items method of Mediawiki for new tests

grimoire_elk/elk/mbox.py
This patch allows to handle through the MBox backend the case when the Date attribute of the JSON items appears in uppercase
=> [elk] Handle NNTP uppercase Date field

grimoire_elk/elk/bugzillarest.py, grimoire_elk/ocean/bugzillarest.py, tests/data/bugzillarest.json
This patch prevents to index summary issues, the content of comments and their descriptions and summaries of attachments. These fields may contain large text that causes ES to fail during data uploading.
=> [ocean] Fix mappings to index BugzillaRest data

grimoire_elk/ocean/crates.py, tests/data/crates.json
This patch prevents to index fine-grained versions and downloads information, which may cause ES to fail in handling to many indexes
=> [ocean] Enhance mappings to index Crates data

grimoire_elk/elk/jenkins.py, grimoire_elk/ocean/jenkins.py
This patch changes how the comments on changeSet items are prevented to be indexed. Thus, the old value "not_analyzed" of the mapping "index" is replaced by "false"
=> [ocean] Replace Jenkins mapping property for changeSet.items.comment

grimoire_elk/ocean/twitter.py, utils/twitter2es.py
This patch reduces the number of indexes created when inserting Twitter data, thus preventing hitting the limit of total fields in index. For each Twitter items, the fields below are not indexed:
- user.entities
- hashtags.indices
- metadata
- entities.symbols
- entities.urls
- entities.user_mentions
=> [ocean] Fix mappings to index Twitter data

grimoire_elk/elk/git.py
Time to commit can be computed as commit date minus author time. This patch does that, creating a new field in the enriched index.
Uploading this on behalf of @BenLloydPearson.
This should close #235 
We're uploading this without proper testing. Please, have a detailed look before accepting.
=> [git] Add a new time_to_commit field to enriched index.

grimoire_elk/ocean/bugzillarest.py, grimoire_elk/ocean/discourse.py, grimoire_elk/ocean/gerrit.py, grimoire_elk/ocean/git.py, grimoire_elk/ocean/github.py, grimoire_elk/ocean/jenkins.py, grimoire_elk/ocean/mediawiki.py, grimoire_elk/ocean/meetup.py, grimoire_elk/ocean/mozillaclub.py, grimoire_elk/ocean/nntp.py, grimoire_elk/ocean/redmine.py, grimoire_elk/ocean/remo.py, grimoire_elk/ocean/rss.py, grimoire_elk/ocean/stackexchange.py
This patch includes ElasticSearch 2.x mappings for several ocean backends. In some cases, the patch also modifies the if condition used to detect the ElasticSearch version
=> [ocean] Add ES 2.x mappings for ocean backends

grimoire_elk/elk/bugzillarest.py, tests/data/bugzillarest-item-bulgarian.json, tests/data/bugzillarest-projects.json, tests/test_bugzillarest.py
The mapping definition for projects is done for bugzillarest like:
```
"Localization": {
"bugzillarest": [
....
"https://bugzilla.mozilla.org/buglist.cgi?product=Mozilla+Localizations&component=bg+/+Bulgarian",
```
White spaces are changed with "+" because the name of the component in the raw items from Bugzilla is: `"component" : "bg / Bulgarian"`. It is done in all cases like that way: only changing " " with "+" (but it is not a urlencode).
This PR implement that.
=> [enrich][bugzillarest] Change " " with "+" in product and component names to follow Mozilla projects mapping

grimoire_elk/arthur.py, grimoire_elk/elastic.py, grimoire_elk/elk/mbox_study_kip.py, grimoire_elk/ocean/elastic.py, utils/index_mapping.py
This code removes the bulk_upload_sync method and replaces its calls with the ones of bulk_upload method, which now takes care of controlling that the changes made are visible to search (by adding the param ?refresh=true to the request).
=> [elastic] Delete bulk_upload_sync method

grimoire_elk/ocean/slack.py
This patch avoids to define dynamic mappings for attachment data. Thus it prevents number format exceptions related to the field data.attachments.ts (which is not recognized as number)
=> [ocean] Prevent Slack attachment info to be indexed

grimoire_elk/elk/bugzilla.py, grimoire_elk/elk/dockerhub.py, grimoire_elk/elk/enrich.py, grimoire_elk/elk/gerrit.py, grimoire_elk/elk/git.py, grimoire_elk/elk/mediawiki.py, grimoire_elk/elk/mozillaclub.py, grimoire_elk/elk/redmine.py, grimoire_elk/ocean/bugzilla.py, grimoire_elk/ocean/gerrit.py, grimoire_elk/ocean/mediawiki.py, grimoire_elk/ocean/redmine.py
This patch limits the content size of keyword fields to 32000, thus it avoids (i) losing items in the raw and enriched indexes (ii) breaking the panel specifications
=> [ocean/elk] Limit content size of keyword fields

grimoire_elk/elk/meetup.py, grimoire_elk/elk/nntp.py, grimoire_elk/elk/rss.py
This patch fixes how the ES version is checked. The parameter of get_elastic_mappings (es_major) is checked against a string (not an integer).
=> [elk] Fix check condition ES version for meetup, nntp, rss

grimoire_elk/elk/redmine.py
This patch targets #257. It fixes the truncation of descriptions during the enrichment of redmine items.
=> [elk] Fix limit description on none values for redmine

grimoire_elk/ocean/jenkins.py
This patch fixes the mappings for jenkins in order to avoid conflicts with the existing mapping on data.changeSet.items.comment.
=> [ocean] Fix mappings with jenkins to avoid regression errors

doc/studies.md
I've included information about index fields being generated. Ideally this should be changed by a link to the corresponding CSVs.
I've also added a broken link to the place where Mordred config documentation should be, please check if this is the right place.
=> [doc] Add documentation for Areas of Code study

grimoire_elk/elk/git.py
This patch allows to handle commits with empty messages. Thus, it includes a condition to check that the attribute message exists in the commit item.
=> [elk] Handle empty message commits

grimoire_elk/enriched/askbot.py
This patch sets the default value of the attribute question_has_accepted_answer to zero for unanswered questions in askbot.
=> [enriched] Set not accepted answer flag to askbot unanswered question

grimoire_elk/enriched/gerrit.py
This patch checks that comments within a review exist, before limiting their size.
=> [enrich] Fix limit comment message in gerrit

grimoire_elk/raw/gerrit.py
This patch fixes the mappings for ES 2.2 defined for gerrit data.
=> [raw] Fix typos in ES 2.2 mappings for gerrit

grimoire_elk/enriched/git.py
This fix handles wrong time offsets of authored and committed dates. Thus, it prevents Value errors related to parsing wrong dates.
=> [enriched] Handle wrong time offset in Git enrichment

grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py
Default timeout is set to 10, now is explicitely set to 100 to
avoid failures when running studies through a slow network
connection.
=> [studies] Add timeout to ES connections

grimoire_elk/enriched/askbot.py, tests/data/askbot.json
This patch initializes the attribute accepted_answer_id to a null value when it is not present in the json returned by the api. Thus, it avoids KeyError exceptions during the enrichment phase.
=> [enrich] Handle missing accepted_answer_id attribute

grimoire_elk/enriched/discourse.py
This patch fixes the mapping of the enriched attribute question_title within the discourse backend. It allows the attribute to be searchable and aggregatable, thus avoiding breaking the corresponding panel.
=> [enrich] Fix mapping for attribute question_title in discourse

grimoire_elk/raw/slack.py
This patch prevents to index attachment-related information which may cause timely errors (due to the timestamp value not always recognized as such by ES). This data is not used in the corresponding panel, as shown in the schema/slack.csv.
=> [raw] Filter attachment-related data of slack messages

grimoire_elk/enriched/jira.py, grimoire_elk/raw/jira.py
This PR allows to handle long fields.description values in the raw and enriched indexes. In the raw index, a mapping is defined to to avoid immense term exceptions, while in the enriched index, the value is truncated to avoid changing the type of the attribute (keyword).
=> [raw/enrich] Handle long description in Jira fields

grimoire_elk/enriched/functest.py, tests/data/functest.json
This patch allows to handle the different formats for failures in functest. In a nutshell, failures are returned by the functest API as number or list. This heterogeneity causes ES to fail since it cannot map different types for the same attribute. Thus, this code stores the lenght of the list in the attribute failures, avoiding type conflicts.
=> [enrich] Handle different formats for failures in functest

grimoire_elk/raw/mbox.py, grimoire_elk/raw/nntp.py
This patch removes from the raw data the custom fields (X-...) to avoid hitting the limit of 1000 fields in ES.
=> [mbox/nntp] Remove X-fields in raw data    

grimoire_elk/raw/phabricator.py, tests/data/phabricator.json
This patch replaces dots in field attribute names with underscores. Thus, it prevents errors on ES versions previous to 5 (which don't allow to store this kind of attributes). For consistency reasons, this fix is applied also to more recent versions of ES.
=> [phabricator] Handle dots in JSON attribute names

doc/studies.md, grimoire_elk/enriched/ceres_base.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py
These commits add functionality to manage aliases after onion and areas of code execution. It is particularly important for onion because each time the study runs, index is deleted and therefore the corresponding alias is automatically removed. This way, once data is available, alias is created if needed.
=> Add alias management to studies

grimoire_elk/elk.py, grimoire_elk/enriched/sortinghat_gelk.py, tests/test_load_identities.py
This PR changes the way of loading identities to sortinghat. In a nutshell, instead of loading in memory all the identities before sending them to sortinghat, they are sent to bulks of 500. Thus, the consuption of memory is safe when dealing with a large number of identities. Furthermore, this PR enables also to log exceptions that may occur when processing identities. This log can help to shed some light on mordred
threads that from time to time die without leaving any trace.
=> [identities] Load identities to sortinghat by bulks

grimoire_elk/raw/jira.py
This patch prevents to index changelog histories of Jira items, thus avoiding immense term exceptions when inserting data to ES.
=> [jira] Handle data.changelog.histories fields

grimoire_elk/raw/jenkins.py
This patch allows to deal with large comments of Jenkins data, thus it avoids immense term exceptions when inserting data to ES.
=> [jenkins] Update raw mappings to deal with large comments

setup.py
When installing grimoire-elk alone, the problem below is found. This patch fixes it by adding sortinghat as a dependency.
This could be a temporary fix, while we decide if this really needs to depend on SoertingHat (now it is a extra dependency, which I didn't remove just in case).
```
$ pip install grimoire-elk
...
$ p2o.py --help
Traceback (most recent call last):
File "/tmp/3/bin/p2o.py", line 30, in <module>
from grimoire_elk.elk import feed_backend, enrich_backend
File "/tmp/3/lib/python3.6/site-packages/grimoire_elk/elk.py", line 39, in <module>
from .utils import get_elastic
File "/tmp/3/lib/python3.6/site-packages/grimoire_elk/utils.py", line 77, in <module>
from .enriched.git import GitEnrich
File "/tmp/3/lib/python3.6/site-packages/grimoire_elk/enriched/git.py", line 37, in …
```
=> [setup] Add dependency on SortingHat

tests/base.py
This patch disables the tests using the CSVs which are currently failing due to not updated/not reviewed CSVs.
=> [tests] Temporary disable tests using CSVs

grimoire_elk/raw/jira.py
This patch disable dynamic mappings when indexing changelog histories of Jira items.
=> [jira] Disable dynamic mappings for data.changelog.histories

grimoire_elk/enriched/stackexchange.py
This code adds to the enriched item information about:
(i) whether a question has an accepted answer,
(ii) the id of the accepted answer.
=> [stackexchange] Add information to track accepted answers

grimoire_elk/enriched/stackexchange.py
This PR targets https://github.com/chaoss/grimoirelab-elk/issues/336. It allows to handle deleted users on stackexchange platforms, which displayed names are now replaced with 'unknown' to avoid sortinghat failing when loading identities.
=> [stackexchange] Handle deleted users

grimoire_elk/elk.py
This patch enables to raise an exception when a study fails, instead of printing the traceback. Thus, it allows Mordred to be aware that a thread has failed.
=> [elk] raise exception in do_studies

grimoire_elk/enriched/git.py, tests/base.py, tests/test_git.py
The Author field has been removed from the enriched index because it contains the email
in some cases and all emails are being removed from enriched indexes in GrimoireLab.
https://github.com/chaoss/grimoirelab-elk/commit/bb66977d8f285f8c6d3fc52bb3ccf6ed1d3cd00b#diff-36823e8b50c4d2b1223f80fff5688bafL335
=> [studies][demography] Use author_id field to aggregate the authors instead of Author

grimoire_elk/raw/jenkins.py
This code enhances the raw mappings for jenkins data to avoid `exceed limit number of fields` exceptions.
=> [raw] Reduce the number of fields indexed for jenkins items

grimoire_elk/enriched/enrich.py
This code sets to 30000 the max length for fields of type keyword, thus preventing immense term exceptions during the creation of enriched items.
=> [enrich] Modify max length for keyword fields

grimoire_elk/enriched/git.py
And author could have several author_id fields so it can not be used to aggregate authors.
=> [studies][demography] Use author_uuid field to aggregate the authors instead of author_id

grimoire_elk/enriched/jira.py, schema/jira.csv
This PR addressed #361, thus it fixes a typo in jira enriched attribute and aligns the change with the corresponding csv schema.
=> [jira] Fix typo in enriched jira fields

grimoire_elk/enriched/stackexchange.py
This patch fixes a bug that was causing to not properly fill the fields `question_accepted_answer_id` and `question_has_accepted_answer` for questions having only one answer (which was marked as accepted).
=> [stackexchage] Fix fields for questions having an accepted answer

grimoire_elk/enriched/ceres_base.py
`latest_date` is used by CeresBase but was not included in the
definition Connector abstract class.
This is not a high priority bug as it does not affect to code execution.
Solves #340
=> [enriched] Add `latest_date` method to connector

grimoire_elk/elastic.py
This code allows to force the format of date fields. Thus, those fields are now formatted according to `strict_date_optional_time||epoch_millis`.
=> [elastic] Add template to force date format

grimoire_elk/raw/bugzilla.py
This code avoids indexing fields within the activity attribute, thus avoiding immense term exception when inserting raw data to ElasticSearch.
=> [bugzilla] Fix immense term exception for activity attribute

grimoire_elk/raw/jira.py
This code reduces the number of indexed fields for jira raw indexes, thus avoiding limit number of fields exceptions thrown by ES when inserting new data.
=> [jira] Fix mapping to avoid limit number of fields exception

grimoire_elk/enriched/github.py
closes chaoss/wg-gmd#8
This PR adds the functionality to calculate the first response to issue duration for an issue/pr by someone other than the user who created the issue/pr and adds it to the enriched index for github data source.
=> Add code to calculate first response to issue duration

.travis.yml, requirements.txt
This code allows to execute the tests using the latest versionsof the grimoirelab components required by E LK, thus simplyfing the testing of features that involve more components. The components are:
- grimoirelab-sortinghat
- grimoirelab-toolkit
- grimoirelab-cereslib
- grimoirelab-kingarthur
- grimoirelab-perceval
- grimoirelab-perceval-mozilla
- grimoirelab-perceval-opnfv
- grimoirelab-perceval-puppet
=> [tests] Allow testing with latest grimoirelab component versions

grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/sortinghat_gelk.py
Due to enhancements in sortinghat, this code aligns the code to handle sortinghat AlreadyExist exceptions in ELK.
=> [sortinghat] Align ELK with changes in sortinghat

grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py
This changes solve #363
It also fixes constructor method, where `insecure` parameter
was not used. `True` was used by default, ignoring the
parameter (which value was in fact `True` by default)
=> [studies] Fix ES conns to use insecure parameter

tests/base.py
When using secure envs, for instance those versions
of Kibiter including Search Guard, test will fail
if certificate cannot be verified. Including this
change, certificate validation is disabled so tests
can be run without the need of a valid certificate.
=> [tests] Add support for test using SSL

grimoire_elk/elk.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py, grimoire_elk/enriched/github.py, grimoire_elk/enriched/mbox.py, tests/base.py
This code adds the ocean backend as parameter for studies. This modification is required since some studies need access to the raw index (which could be stored in a different machine).
=> [enrich] Include ocean backend to studies

grimoire_elk/enriched/github.py, grimoire_elk/raw/github.py
The main aim of this PR is to trigger the discussion about how to integrate GitHub pull request data in GrimoireLab. This PR proposes to extend GitHubOcean and GitHubEnrich to include the new data without creating [a new connector](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/utils.py#L189). Conversely, PR https://github.com/chaoss/grimoirelab-elk/pull/398 proposes to add a new connector to ELK.
This PR requires a modification to mordred (PR https://github.com/chaoss/grimoirelab-sirmordred/pull/175) in order to allow the definition of multiple sections for the same backend (thus enabling the explotation of backends with multiple categories in a transparent way). On the other hand, PR https://github.com/chaoss/grimoirelab-elk/pull/398 doesn't need to modify mordred, …
=> [enriched] Add support for github pull request data

grimoire_elk/enriched/github.py
Added code to calculate
- Enriched PR data
- The following GMD code development metrics:
- forks
- code merge duration
- number of review comments
- Maintainer Response to Merge Request Duration
closes #394
=> [enriched] Add code to calculate github pull requests enriched data

grimoire_elk/enriched/twitter.py
This code uses the perceval attribute `metadata__updated_on` to search raw tweets and enrich them. This change is due to the fact that the attribute `created_at` in tweets is not recognized by ElasticSearch as a valid date, thus, the raw tweets are not enriched and not visualized in dashboards.
=> [enriched] Use metadata__update_on to index tweets

grimoire_elk/elastic_items.py
This code removes the condition to sort twitter items based on the old attribute `@timestamp`.
=> [elastic_items] Remove condition for old twitter items

grimoire_elk/enriched/ceres_base.py, grimoire_elk/enriched/study_ceres_aoc.py
When no events are extracted from a set commits, i.e.,
there are no file actions, ignore that block and continue
processing the next batch of commits.
=> [aoc] Fix study to do nothing if no events

grimoire_elk/enriched/git.py, grimoire_elk/enriched/github.py
This code adds the `enrich_pull_requests` study to the enriched/github.py
file. This study aims at adding additional fields that are related to
pull request items but are not fetched by perceval directly for items of the
pull_requests category.
This study should be used using the functionality added by the PR:
https://github.com/chaoss/grimoirelab-sirmordred/pull/190.
This study takes in an input param: `raw_issues_index` which should contain
the data fetched from the same repository from which the pull requests data
is fetched. Using this `raw_issues_index`, the additional data is extracted from
related issue and that data is enriched and added to the relevant pull request
and updated in the enriched pull request index.
The specific fields that are added after running the study are:
- …
=> [studies] Add enrich_pull_requests study

grimoire_elk/enriched/slack.py, tests/data/slack.json, tests/test_slack.py
This code uses the attribute `num_members` in a Perceval Slack JSON doc to count the members of a Slack channel. However, in order to avoid breaking changes, the former variable `member` is kept and used only if `num_members` is not present in the input document.
=> [enrich-slack] Use `num_members` attribute to count channel members

grimoire_elk/enriched/study_ceres_aoc.py
This code replaces the content of commit messages with empty str, in order to limit the size of enriched indexes.
=> [aoc] Replace message commit with first 80 chars

grimoire_elk/enriched/mediawiki.py, tests/test_mediawiki.py
Due to a wikimedia API change, the old way of creating a URL is not valid anymore. Thus, this code proposes a new way to form the URLs, allowing to access the corresponding pages via the kibiter dashboard.
=> [enrich-mediawiki] Change way url is created

grimoire_elk/enriched/git.py, tests/data/git.json, tests/test_git.py
This code allows to handle commits for which no author/committer are defined. For these (rare) cases, the name of the user is set to `Unknown`, while the email to None.
=> [enrich-git] Handle commits with missing user info

grimoire_elk/enriched/jira.py
This code improves the Jira enricher by:
- replacing the term `assignee_to` with `assignee` (the former doesn't appear to be valid, since it's not defined in the corresponding CSV file).
- aligning the logic to extract identities to the one in the github enricher.
=> [enrich-jira] Improve jira enricher

grimoire_elk/enriched/jira.py, tests/data/jira.json, tests/test_jira.py
This code sets all `assignee_name`, `assignee_org_name` and`assignee_user_name` null attributes of issues to `Unassigned`, thus avoiding to visualize results with no values.
=> [enriched-jira] Set Unassigned to null assignee orgs and usernames

grimoire_elk/enriched/stackexchange.py, tests/data/stackexchange.json
So far, Stack Exchange enriched answers did not contain these two attributes. This caused some errors, like to assing a project to an answers due to the mapping between project and answers was done using 'origin' field.
Fixes #436.
=> [enrich-stackexchange] Add 'origin' and 'tag' fields to answer items

grimoire_elk/enriched/mediawiki.py
By default, the unique id of an item is the `uuid` that comes from Perceval which is also used to update items during autorefresh operations. In the case of mediawiki, the unique id of an item
relies on the revision id (`revision_revid`). Thus this code removes the method `get_field_unique_id_review` and uses its content to overwrite the `get_field_unique_id` method, avoding in this way misalignments between the unique id used for enrichment and autorefresh operations.
=> [enrich-mediawiki] Fix unique id for enriched items

grimoire_elk/enriched/enrich.py, tests/test_enrich.py, tests/test_git.py
When there are identities that are not found in SortingHat, the fields in the enriched items related to those identities are set to an empty string (''). When someone sees this value, it is not clear either there is an error in the visualization, in the way this value was obtained or if the value was blank in the origin.
For these reasons, the new default value will be "-- UNDEFINED --", so these kind of problems can be tracked more easy.
=> [enrich] Set identities fields to UNDEFINED for null values

grimoire_elk/enriched/stackexchange.py
This code allows to prevent keyerror exceptions over a question having `answer_count` greater than 0 but not list of `answers` associated.
=> [enrich-stackexchange] Handle KeyError exception

grimoire_elk/enriched/gitlab.py, tests/data/gitlab.json, tests/test_gitlab.py
This code adds milestone information to enriched items coming from gitlab issues and merge requests. Milestone data is stored in the attribute `milestone`, in case no milestone is present, the value is set to `no-milestone`. Tests have been modified accordingly.
=> [gitlab] Add milestone attribute to enriched items

grimoire_elk/enriched/git.py
Out index name is now accesible as a constant within Git class.
=> [aoc] Add a constant for out_index default value 

grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/gitlab.py
This PR adds onion studies for GitLab issues and merge requests. Each onion study requires 3 params at least: `in_index`, `out_index` and `data_source` (which should be either `gitlab-issues` or `gitlab-merges`).
```
[gitlab:issue]
raw_index = test_gitlab-issue-raw
enriched_index = test_gitlab-issue
api-token = ZAxX9AbUdV4HXkpyiuHV
no-archive = true
sleep-for-rate = true
studies = [enrich_onion:gitlab-issue]
[gitlab:merge]
raw_index = test_gitlab-merge-raw
enriched_index = test_gitlab-merge
api-token = ZAxX9AbUdV4HXkpyiuHV
no-archive = true
category = merge_request
sleep-for-rate = true
studies = [enrich_onion:gitlab-merge]
[enrich_onion:gitlab-merge]
in_index = test_gitlab-merge
out_index = gitlab_merges_onion
data_source = gitlab-merges
[enrich_onion:gitlab-issue]
in_index = …
```
=> [gitlab-enrich] Add onion study

grimoire_elk/enriched/ceres_base.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py, grimoire_elk/enriched/github.py, grimoire_elk/enriched/gitlab.py, grimoire_elk/enriched/study_ceres_onion.py
A new parameter `seconds` can be used to define the minimum
time from one study execution to the following. By default has
been set to one week, but can be set for each data source in
`setup.cfg`. Onion will only run again if at least that number
of seconds has passed from the enrichment of the most recent
item in the index.
For information purposes, each time the study is not run due
to this parameter, a log line is printed containing that
minimum date for reference.
Note that the study won't be executed exactly at that time,
but at some point after that time. Studies are executed
after each enrichment processes.
A second commit has been included to solve a bug that prevented the alias to be created after executing the study in some cases:
```
[onion] Fix `all_onion` alias creation  … …
```
=>  [onion] Add refresh interval

grimoire_elk/enriched/bugzilla.py
This code replaces the list used in the method `get_identities` with a yield, thus reducing the memory footprint.
=> [enrich-bugzilla] Replace list with yield

grimoire_elk/enriched/mattermost.py
This PR address two problems in the Mattermost enricher:
* creation of a white space name (i.e " ") when the first and last name of the identities are empty
* set empty string values when the email of an identity is not available
=> Fix Mattermost generation of values for emails and names on identities

grimoire_elk/enriched/rss.py
=> [enrich-rss] Replace list with yield

grimoire_elk/enriched/mozillaclub.py
=> [enrich-mozillaclub] Replace list with yield

grimoire_elk/enriched/mediawiki.py
=> [enrich-mediawiki] Replace list with yield

grimoire_elk/enriched/gitlab.py
=> [enrich-gitlab] Replace list with yield

grimoire_elk/enriched/bugzillarest.py
=> [enrich-bugzillarest] Replace list with yield

grimoire_elk/elk.py, grimoire_elk/enriched/dockerhub.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/functest.py, grimoire_elk/enriched/google_hits.py, grimoire_elk/enriched/jenkins.py, grimoire_elk/enriched/telegram.py, tests/test_dockerhub.py, tests/test_enrich.py, tests/test_functest.py, tests/test_google_hits.py, tests/test_jenkins.py
This PR prevents to execute the load identites operation for those enrichers that don't return items with identities data. Thus, the proposed code improves the performance of the platform.
=> [elk] Add condition to skip loading identites

grimoire_elk/enriched/gitlab.py, tests/data/gitlab.json, tests/test_gitlab.py
This code handles old raw items coming from the GitLab API that don't contain the milestone attribute.
=> [enrich-gitlab] Handle missing milestone attribute in raw items

grimoire_elk/enriched/enrich.py
This code prevents to insert SH identities with all empty fields. A warning is generated to notify the user.
=> [enrich] Handle insertion of empty identities

grimoire_elk/enriched/stackexchange.py, schema/stackoverflow.csv, tests/data/stackexchange.json
This code reorganizes the tags fields for questions and answers.
+ Enriched answers include the fields:
- `answer_tags` (tags of the answer)
- `question_tags` (tags of the question)
+ Enrich questions include the fields:
- `question_tags` (tags of the question)
- `answers_tags` (all tags of answers)
- `thread_tags` (the sum of question and answers tags)
=> [enrich-stackexchange] Reorganize tags fields

grimoire_elk/enriched/phabricator.py
This code replaces the list used in the method `get_rich_events` with a yield, thus reducing the memory footprint.
=> [enrich-phabricator] Replace list with yield

grimoire_elk/enriched/crates.py
This code replaces the list used in the method `get_rich_events` with a yield, thus reducing the memory footprint.
=> [enrich-crates] Replace list with yield

grimoire_elk/elastic_items.py
This code allows to handle none page value returned by `get_elastic_items`.
=> [elastic_items] Handle none page

grimoire_elk/enriched/github.py
This code fixes the value of the attribute repository, which is now derived from the origin. This modification is needed for GitHub repos that changed their names and for which the corresponding attribute `html_url` was not updated.
=> [enrich-github] Fix attribute repository

grimoire_elk/elastic.py, grimoire_elk/elastic_items.py, grimoire_elk/elk.py, grimoire_elk/enriched/dockerhub.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py, grimoire_elk/enriched/github.py, grimoire_elk/enriched/kitsune.py, grimoire_elk/enriched/mbox.py, grimoire_elk/enriched/mbox_study_kip.py, grimoire_elk/enriched/mediawiki.py, grimoire_elk/enriched/mozillaclub.py, tests/test_enrich.py, tests/test_gerrit.py, tests/test_git.py
This PR allows to remove credentials (username and password) from the log messages which track the URLs that interact with the ElasticSearch server. Thus, it avoids possible security leaks when copy/paste traceback errors in no-safe environments (GitHub, GitLab).
=> [ELK] Remove credentials from log messages

grimoire_elk/enriched/askbot.py, grimoire_elk/enriched/discourse.py, schema/askbot.csv, schema/discourse.csv
This PR updates the mapping for the attribute id, which is generated as a concatenation of ids (e.g., question + answer + comment). The corresponding schema (askbot.csv) has been changed accordingly.
=> Fix askbot mappings enrich

grimoire_elk/enriched/enrich.py
This code prevents to query SortingHat when the ids returned by the utils.uuid is none.
=> [enrich] Prevent find identities for none ids

grimoire_elk/enriched/gitlab.py
This PR updates the way the attribute `time_to_close_days` is calculated. In GitLab a merge request can end up in two states, merged and closed. The former concerns merge requests that were finally merged to the code base, while the latter represents rejected merge requests. Given the aforementioned workflow, the code has been changed accordingly. Furthermore, this PR fixes also the calculation of the attribute `merged`, which before was always set to true.
=> [enrich-gitlab] Fix GitLab enricher

grimoire_elk/elastic_items.py, grimoire_elk/elk.py, grimoire_elk/enriched/enrich.py
This PR replaces the use of the connector name with the cfg section name to retrieve the project name associated to a data source. 
In a nutshell, initially the connector name had a one-to-one correspondence with the cfg section name, which was used to get the project name in the projects.json. Recently, the cfg section name has been enhanced to include also an identifier (e.g., [gitlab:issue]), thus the connector name cannot be used anymore to find the project name and must be replaced with the cfg section name (which is now propagate from mordred to ELK).
Note that in case the cfg section name is null (this is the case when executing the tests in ELK), the connector name is used.
=> [ELK] Use the cfg section name to retrieve project name

grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py
This PR prevents to create the aliases for studies _demographics_, _onion_ and _areas of code_ if these aliases are already used on another indexes.
To test the PR, you can use micro-mordred with the following configuration and projects.json
**setup.cfg**
```
...
[git]
raw_index = git_chaoss_180804
enriched_index = git_chaoss_180804_enriched_180804
category = commit
studies = [enrich_demography:git, enrich_areas_of_code:git, enrich_onion:git]
[enrich_demography:git]
date_field = utc_commit
author_field = author_uuid
[enrich_areas_of_code:git]
#no_incremental = true
in_index = git_chaoss_180804
out_index = git-aoc_chaoss_enriched_180804
[enrich_onion:git]
in_index = git_chaoss_180804_enriched_180804
out_index = git-onion_chaoss_enriched_180804
contribs_field = hash
no_incremental = false …
```
=> [studies] Prevent create aliases already in use

grimoire_elk/elastic.py, tests/test_enrich.py, tests/test_git.py
This code changes the log message level from warning to debug when an alias already exists. This change aims at reducing the size of logs produced by the platform. The corresponding test has been changed accordingly. 
An additional fix has been provided to ensure the removal of the onion index at the end of the corresponding test. This was needed due to the fact that study aliases cannot be used in more indexes at the same time.
=> [elastic] Change log message level when alias already exists

grimoire_elk/elastic_items.py, grimoire_elk/elk.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py, grimoire_elk/raw/elastic.py
This PR allows to handle deleted commits in Git raw and enriched indexes. 
A generic method `update_items` is included for raw and enriched connectors in order to update the corresponding indexes just after the collection and enrichment operations. For the case of Git, at the end of the enrichment, the list of current commit SHAs is retrieved from the repository and compared with the hashes stored in the raw index. The different of these two sets gives the deleted commits (the ones that are stored in ES but not present in the repo), which  are finally deleted from the raw and enriched indexes.
=> [ELK] Handle deleted commits

grimoire_elk/elk.py, grimoire_elk/enriched/enrich.py, grimoire_elk/raw/gerrit.py
This PR allows to filter a part of the raw data for enrichment. In a nutshell, this is done by including the param `--filter-raw` in the repo within the projects.json. Later, ELK automatically creates a filter
to retain only the data that match the value of `filter-raw`.
=> [gerrit] Allow partial enrichment based on `--filter-raw`

grimoire_elk/elastic.py
This code changes the log level of the message produced when an alias is already in use.
=> [elastic] Change log level message when alias is already in use

grimoire_elk/enriched/enrich.py
This commit removes the check for `all_onion` alias that
prevents its creation if it is already in use. This check
only allowed to link one data source to the alias, so onion
data for the rest of the sources remained unlinked.
=> Remove alias in use check for onion

grimoire_elk/elastic.py, grimoire_elk/enriched/utils.py
This PR allows to include the `filter-raw` param to identify the last date of enrichment for a given index composed by items having the same origin, but coming from different projects (bugzilla, gerrit, jira). 
In a nutshell, the current way of calculating the last date of enrichment takes into account only the origin and the `metadata_timestamp`, while the proposed solution includes also the `filter-raw` param, thus allowing to identify the last date of enriched items for a given filter (e.g., project).
=> [elk] Use filter-raw to get the last enrich date

grimoire_elk/elastic_items.py
This code changes the behaviour of the ES query to retrive items from the raw indexes for incremental enrichment purposes. In a nutshell, the query now uses a QUERY context which returns the items matching the query plus a score that rates how good the match is. However the score is not needed in ELK, thus the content is changed to FILTER context, which doesn't calculate any score.
=> [elastic_items] Update ES query for incremental enrichment

grimoire_elk/enriched/mbox.py, schema/mbox.csv, tests/data/mbox.json, tests/test_groupsio.py, tests/test_hyperkitty.py, tests/test_mbox.py, tests/test_nntp.py, tests/test_pipermail.py
This code includes the new field `mbox_author_domain` in the enrich data. It contains the email address of the sender not processed by SH. Tests and schema have been updated accordingly.
=> [enrich] Add mbox_author_domain to mbox data

grimoire_elk/enriched/git.py, schema/git.csv
This code updates the information about Git references of the items corresponding to commits in both raw and enriched indexes. The update is needed due to operations (e.g., mergesand branch deletions) which affect the repository references and consequently their commits. Thus, this code aims at ensuring consistency between the information of the original Git repository and the data stored in ElasticSearch.
Note that the enriched Git items have been modified to include the refs info, which was not present there. It may be needed to update the corresponding Git schema and panels, which could be done in another PR.
I performed some performance tests with the grimoirelab-perceval repo:
- 18-19 secs disabling `update_commit_references`
- 38-39 secs enabling `update_commit_references`
=> [enrich] Update Git references data in raw and enriched indexes

grimoire_elk/enriched/git.py
This code allows to handle empty Git repositories when updating the the content of the enriched index to remove commits which are not present anymore in the original repository.
=> [enrich] Handle Perceval errors on Git repos when updating items

grimoire_elk/raw/confluence.py
This code allows to parse the filter raw information from the entries within the mordred projects.json.
The projects.json should be changed to the following way:
`"concourse-url --filter-raw=data._expandable.space:/rest/api/space/your-project"`
=> [raw] Handle filter raw for confluence

grimoire_elk/raw/jira.py, tests/data/projects-release.json, tests/test_jira.py
This PR allows to parse the filter raw information from the entries within the mordred projects.json. The projects.json should be changed to the following way:
`jira-url --filter-raw=data.fields.project.key:TARGET-PROJECT-KEY`
Tests have been added.
=> [raw] Handle filter raw for jira

grimoire_elk/enriched/git.py, grimoire_elk/enriched/utils.py, schema/git.csv
This code allows to update the branch information of the JSON documents representing Git commits. First the list of branches is cleared in the enriched index, then the original repo is queried to retrieve the list of commit hashes for each branch and finally the obtained hashes are added to the branches attribute of the documents.
Git schema and enrich/utils have been updated. The former now includes the `branches` attribute, the latter enables the retry mechanism for 409 HTTP errors, which may occur for the operations `update_by_query` and `delete_by_query`.
Find below some performance tests:
- perceval
- without branch update: 4 secs
- with branch update: 5 secs
- mordred
- without branch update: 4 secs
- with branch update only for enrich: 1min20secs
- elastic/kibana
- withouth branch …
=> [enrich] Update branch info in git commits

grimoire_elk/elastic_items.py, grimoire_elk/elk.py, grimoire_elk/enriched/utils.py, grimoire_elk/raw/askbot.py, grimoire_elk/raw/bugzilla.py, grimoire_elk/raw/confluence.py, grimoire_elk/raw/elastic.py, grimoire_elk/raw/gerrit.py, grimoire_elk/raw/git.py, grimoire_elk/raw/jira.py, tests/test_elastic_ocean.py
This PR redefines the method `get_p2o_params_from_url` to parse the filters declared in the projects.json entries. Filters are identified by the delimiter `--filter`, while the filter name and values are separated by `=`. For instance:
- `https://bugzilla.mozilla.org --filter-raw=data.product:Add-on SDK,data.component:General`
- `http://finosfoundation.atlassian.net --filter-raw=data.fields.project.key:ODP`
- `https://github.com/chaoss/grimoirelab-elk --filter-raw-prefix=data.files.file:README,data.files.file:perceval`
The code provided applies for the Perceval backends that require only an URL as input parameter, for the others, the method `get_p2o_params_from_url` should be redefined. Unit tests have been provided for the new method and live tests have been executed on the following …
=> [raw] Parse filters passed in the projects.json entries

grimoire_elk/enriched/mediawiki.py
This code handles revisions which have their editor hidden, which are marked as `HIDDEN_EDITOR`.
=> [enriched] Handle hidden editors in mediawiki revisions

grimoire_elk/elk.py
This code removes the filter-raw and filter-raw-prefix which were set in the `enrich_backend` function but not used by the enrich backend.
=> [elk] Remove filter-raw-* for enrich backend

grimoire_elk/enriched/confluence.py, schema/confluence.csv, tests/data/confluence.json, tests/test_confluence.py
This patch enriches Confluence items with two new fields related to ancestors data.
The field 'ancestors_titles' is a list with the titles of each ancestor, and the field 'ancestors_links' which is a list with the relative links to each ancestor page.
This PR fixes #571
=> [enrich-confluence] Add ancestors data to enriched items

utils/p2o.py
This code includes a none value for the param `cfg_section_name`, which was recently added to the method `enrich_backend` in elk.py.
=> [p2o] Add None value for param `cfg_section_name` to p2o

grimoire_elk/enriched/gerrit.py
This code includes the onion study to gerrit. Thus, now an onion study can be defined via the setup.cfg of modred.
=> [enrich] Add onion study to gerrit

grimoire_elk/elk.py, grimoire_elk/enriched/bugzilla.py, grimoire_elk/enriched/bugzillarest.py, grimoire_elk/enriched/enrich.py, tests/data/bugzillarest-projects.json, tests/test_projects.sql
This PR assigns the default project name `Main` to the items coming from the repos included in the `unknown` section within the projects.json. Furthermore, it also removes the method `get_item_project` within the bugzillarest enricher, which logic is not needed anymore (since related to the previous implementation of `--filter-raw`).
=> [elk] Handle project name for filtered repos

grimoire_elk/elastic_items.py, grimoire_elk/elk.py, grimoire_elk/enriched/utils.py
This PR fixes the incremental enrichment for repos having the filter-raw param. In a nutshell, the last enriched item is calculated in mordred (TaskEnrich) before starting enriching the single repos which data is copied to the same enriched index.
In case of a faulty enrichment execution, the number of raw and enriched items doesn't match, thus the enriched index should be recreated to avoid losing items.
=> [elk] Fix incremental enrichment for filter-raw repos

grimoire_elk/enriched/github.py, schema/github_repos.csv, tests/test_github.py
This commit adds the missing URL field to GitHub repository items. Thus, it is aligned in data with 'issue' and 'pull_request' category items.
=> [enrich-github] Add url field to enriched repository items

tests/data/finosmeetings.json
Due recent changes in FINOS Meetrings backend, some of the fields of the raw items have been renamed. This commit updates tests data to align them with the current backend.
=> [tests] Update finosmeetrings backend test to the new schema

grimoire_elk/enriched/stackexchange.py
This code handles enriched items not having `answer_tags` field. Thus, it prevents the error KeyError: 'answer_tags'.
=> [stackexchange] Handle missing `answer_tags`

grimoire_elk/enriched/jira.py
This code adds the mapping to the Jira enriched items to avoid ES mapping errors on the attribute `release`, which may be wrongly detected as date.
=> [jira] Handle multiple type values in `release` attribute during enrichment

grimoire_elk/enriched/jira.py
This code handle missing fields that are used to create the
enriched items. In particular, it checks that the following
fields exist:
- issue.fields.creator
- issue.fields.assignee
- issue.fields.resolution
=> [jira] Handle missing fields during the enrichment

grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py
This code adds the param `retry_on_timeout` when initializing the ElasticSearch DSL object, thus preventing Gateway Timeout.
=> [enrich] Prevent timeout when using ElasticSearch DSL

grimoire_elk/elk.py, grimoire_elk/enriched/meetup.py, grimoire_elk/raw/elastic.py
This code allows to pass the value of the filter-classifed param defined in the setup.cfg to Perceval. The methods `elk.feed_backend` and `elastic.feed` have been refactored to handle the new parameter.
=> [elk] Handle filter-classified param

grimoire_elk/elastic.py, grimoire_elk/elk.py, grimoire_elk/enriched/sortinghat_gelk.py, grimoire_elk/enriched/utils.py, grimoire_elk/utils.py
This PR allows to delete unique identities from SortingHat according to a retention time window. The deletion occurs in two ways, the former checks that the deleted unique identities in the enriched indexes are not present in SortingHat, the latter checks that all unique identities in SortingHat are the ones present in the enriched indexes (thus avoiding to store orphan identities which would fall outside the retention time window.)
In a nutshell the proposed code works as follow. For every enrich iteration, the identifiers of the unique identities in the enriched items are retrieved and stored in the index `grimoirelab_identities_cache` together with the time when they were found (`last_seen`). In case the data retention policy is on, the `grimoirelab_identities_cache` index is used to …
=> [elk] Remove identities

grimoire_elk/enriched/confluence.py, tests/data/confluence.json, tests/test_confluence.py
This code handles ancestors which miss the title attribute. Tests have been provided accordingly.
=> [enriched] Fix missing ancestor title in confluence enriched items

grimoire_elk/enriched/git.py
Calls for the git command `rev-list` are wrapped in try..except blocks to deal with production environments which use a Git version not supporting this command.
=> [enrich-git] Handle rev-list command failures

grimoire_elk/elk.py, grimoire_elk/enriched/meetup.py
Due 'rsvps' is a classified field, it might not be available when items are retrieved. So far, this field is considered as mandatory by the enricher.
With this patch, ELK won't break when this field is not found.
This patch addresses the changes proposed in #599. 
`venue` and `event_hosts` are already skipped when they are not found in a raw item.
=> [enrich-meetup] Avoid failures when 'rsvps' field is not available

grimoire_elk/enriched/git.py
The try..except block including the rev-list call in the method `add_commit_branches` is extended since the call returns a generator, thus the result of the call is calculated afterwards.
Signed-off-by: Valerio Cosentino valcos@bitergia.com
=> [enriched-git] Fix handling rev-list command error

grimoire_elk/elk.py
This code allows to ignore the uuid attributes which contain empty values, thus avoiding ES errors when inserting items with empty `_id`.
=> [elk] Handle empty sh uuid attributes

grimoire_elk/elastic_items.py, tests/test_elastic_items.py
This code allows to handle commas defined in the values of the filter-raw param within the projects.json. To achive this, the split match is changed to include also the str `data.`.
=> [elastic_items] Handle commas in filter-raw

grimoire_elk/elastic.py
This code checks the presence of the attribute `properties` in an enriched index. This check is needed to avoid errors when extracting properties from empty indexes.
=> [elastic] Check presence of `properties` in mappings

grimoire_elk/elastic_items.py, grimoire_elk/elk.py, grimoire_elk/enriched/enrich.py
This PR proposes to simplify the logic to assign project to enriched items. Currently the assignment is based on the logic of the method `get_project_repository` redefined in each enricher, plus a fallback option based on the inspection of the projects.json, which is passed from mordred to ELK. The new approach passes to ELK also the repo (`projects_json_repo`) in the projects.json (which includes the perceval params plus optionally other params such as filter-raw, filtera-raw-prefix, blacklist-ids, proper of some specific enrichers) currently analyzed. Thus, the assignment of the project is done by looking for a perfect match between the value of the `projects_json_repo` in the projects.json, in case the `projects_json_repo` is None, the previous logic is used.
This PR should be reviewed …
=> [ELK] Simplify logic to assing project to enriched items

grimoire_elk/raw/jira.py
This PR modifies the raw mappings to handle comment bodies longer than the maximum length allowed for keywords. Thus, comment bodies are mapped as text.
=> [raw-jira] Update raw mapping to avoid immense term errors

grimoire_elk/enriched/bugzillarest.py
This code changes the logic to assess the number of days a bug is open. It relies on the attribute `is_open`, if the latter exists and is False, the `timeopen_days` is the diff between the creation time and the date of the last change, in all other cases the `timeopen_days` is set to the diff between the creation time and the date when the enriched item was processed by ELK.
=> [enriched-bugzillarest] Change logic to calculate `timeopen_days`

grimoire_elk/enriched/study_ceres_aoc.py
AOC splits each commit into files and sometimes the number
of resulting events is too big for a single bulk upload.
This change splits the list of resulting documents into chunks
of 2k items to make sure the upload is under control.
Signed-off-by: Alberto Pérez García-Plaza <alpgarcia@bitergia.com>
=> [aoc] Update write method to upload smaller lists

requirements.txt, setup.py
This PR constraints the dependencies to elasticsearch and elasticsearch-dsl which are now:
- elasticsearch==6.3.1
- elasticsearch-dsl==6.3.1
=> [ELK] Constrain elasticsearch-related dependencies

grimoire_elk/enriched/study_ceres_aoc.py
This PR limits the number of items returned by paginated searches to 500. This change should reduce the risk of getting `BytesStreamOutput cannot hold more than 2GB of data` errors when reading data from ElasticSearch.
=> [enriched-study-ceres-aoc] Limit search size to 500

grimoire_elk/enriched/functest.py, schema/functest.csv, tests/data/functest.json, tests/test_functest.py
This PR changes the way of assessing the duration time of tests. It relies on `start_date` and `stop_date`, which are used to calculate the duration of a test. The result is stored in the enriched attribute `duration`. To ensure compatibility, the old way (based on the `duration` attribute included in `details`) is stored in the enriched attribute `duration_from_api`.
=> [enriched-functest] Handle no float duration times

grimoire_elk/enriched/discourse.py
This code forces the type of the score attribute to float, thus preventing ElasticSearch to thrown errors due to the assignment of different types to scores (`illegal_argument_exception`).
=> [enriched-discourse] Force type of score attribute to float

grimoire_elk/enriched/gerrit.py
This code changes the way the ids of the enriched items are composed to allow the existence of items from different gerrit servers in the same enriched index.
=> [enriched-gerrit] Handle gerrit items from multiple servers

grimoire_elk/enriched/mediawiki.py, tests/test_mediawiki.py
This code includes the attribute `grimoire_creation_date` to the enriched items generated by the mediawiki enricher.
=> [enriched-mediawiki] Add `grimoire_creation_date` field

grimoire_elk/enriched/gitlab.py, schema/gitlab_issues.csv, schema/gitlab_merges.csv, tests/test_gitlab.py
This code includes the attributes `milestone_start_date` and `milestone_due_date` to the enriched items. They are extracted from the milestone information included in issues and merge requests. For milestone not having start or due dates, their corresponding values in the enriched items are set `None`.
Tests and schemas have been updated accordingly.
=> [enriched-gitlab] Add milestone start and due dates

grimoire_elk/enriched/jira.py, tests/data/jira.json, tests/test_jira.py
This code modifies the way of creating ids (which now include the `uuid` of the corresponding raw items) for enriched items to handle data from multiple jira instances.
=> [enriched-jira] Handle enriched items from multiple jiras

grimoire_elk/raw/slack.py, tests/test_slack.py
This code prevents to index the field `data.channel_info.previous_names`,
thus avoiding mapping_parsing_exception.
=> [raw-slack] Remove channel_info.previous_names attribute

grimoire_elk/enriched/gerrit.py, tests/test_gerrit.py
This PR allows to include metadata such as backend name, elk version and enriched_on to the enriched items. Furthermore, it allows to refresh identites data for the following roles: "author", "by", "changeset_author", "reviewer", "uploader".
=> [enriched-gerrit] Add elk metadata and enable refresh identities

grimoire_elk/enriched/confluence.py
In some cases, Confluence provides users email addresses. This patch adds that value to the SortingHat indentity.
=> [enriched-confluence] Add email data to SH identity

schema/github_pull_requests.csv
This commit adds a new CSV documenting the GitHub Pull Requests only index.
It is based on data generated using master branches in all GrimoireLab projects so should be up to date.
=> [schema] Add CSV documenting Github PRs index

requirements.txt, setup.py
This code fixes the urllib3 version used by ELK to 1.22, since in the later versions urllib3.exceptions.SSLError exceptions may be thrown due to CERTIFICATE_VERIFY_FAILED. Furthermore, it also sets the version of requests to 2.18.2, which is compatible with urllib3 1.22.
=> [dependencies] Pin urllib3 and requests dependencies

.travis.yml, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py, requirements.txt, setup.py
This PR updates the statements that initialize the Elasticsearch objects (imported from the library elasticsearch) to use `RequestsHttpConnection` as connection class, thus avoiding `elasticsearch.exceptions.SSLError: ConnectionError` exceptions. Furthermore the dependencies of urllib3 and requests are also updated, since urllib3 1.22 is affected by a high severity security vulnerability.
=> Fix elasticsearch.exceptions.SSLError: ConnectionError

grimoire_elk/enriched/enrich.py
This code reduces the number of messages logged when retrieving identity information from SortingHat. To this purpose, a check is added to verify that the identity returned by SortingHat is not None, and log messages missing identities and invalid values are set to `debug` level.
=> [enriched-enrich] Reduce number of log messages on identity retrieval

grimoire_elk/enriched/bugzilla.py, grimoire_elk/enriched/bugzillarest.py, grimoire_elk/enriched/discourse.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/gerrit.py, grimoire_elk/enriched/git.py, grimoire_elk/enriched/jira.py, grimoire_elk/enriched/mbox.py, grimoire_elk/enriched/mediawiki.py, grimoire_elk/enriched/mozillaclub.py, grimoire_elk/enriched/redmine.py
This PR limits the number of chars for a string mapped as keyword to 1000 chars. The change is needed to to avoid max_bytes_length_exceeded_exception errors, which may occur when the UTF8 encoding is longer than the max length allowed for keyword attributes (32766 bytes). Furthermore, this PR updates the name of the variable `KEYWORD_MAX_SIZE` to `KEYWORD_MAX_LENGTH`, which seems to be more appropiated.
=> [enriched-enrich] Decrease max keyword size

grimoire_elk/enriched/meetup.py, tests/test_meetup.py
This code converts the attributes `meetup_time`, `meetup_created` and `meetup_updated` to a date
and store it in isoformat. Tests have been added accordingly.
=> [enriched-meetup] Store created, time, updated as date

grimoire_elk/elastic.py, grimoire_elk/enriched/askbot.py, grimoire_elk/enriched/github.py, grimoire_elk/enriched/meetup.py, grimoire_elk/enriched/phabricator.py, grimoire_elk/enriched/stackexchange.py, grimoire_elk/enriched/utils.py, grimoire_elk/raw/elastic.py
This PR removes the function `unixtime_to_datetime` in enriched/utils.py, which was a copy of `datetime.unixtime_to_datetime` in grimoirelab-toolkit. Furthermore, it replaces the use of datetime and dateutil calls with their equivalent in grimoirelab-toolkit. Other enrichers (e.g., bugzilla) are still using direct datetime and dateutil calls, however they can be addressed in a new PR.
=> [elk] Use grimoirelab-toolkit datetime functions

grimoire_elk/elastic.py
This code replaces the use of ValueError exception with InvalidDateError of grimoirelab-toolkit.
=> [elastic] Use InvalidDateError in `get_last_item_field`

grimoire_elk/elk.py, grimoire_elk/raw/elastic.py
Fixes: #642 
@jgbarah @valeriocos Please do have a look, let me know if any changes required.
Thanks!
TODO:
Signed-off-by: inishchith <inishchith@gmail.com>
=> [elk] Add option to fetch from selected branches

grimoire_elk/enriched/mediawiki.py, tests/test_mediawiki.py
This code changes the way of calculating the `grimoire_creation_date`, which is now derived
from the timestamp of each revision. Revisions can be of 2 types: `iscreation` (if parent is None) or `isrevision` (if parent isn't None).
Tests have been provided accordingly.
=> [mediawiki] Fix grimoire_creation_date calculation

setup.py
Pypi now wants that the format of the long description for a package is detailed in the variable long_description_content_type, in setup.py. The good news is that it now supports Markdown, without
any need to convert it to reST.
=> Fix format type for long description of packge.

grimoire_elk/enriched/jira.py, schema/jira.csv, tests/test_jira.py
For every issue, this code creates 3 enriched items which contain creator, assignee and reporter data. The enriched items have type issue and one of the following user_type: creator, assignee and reporter. This change eases the way of counting contributions of each user.
Tests have been added accordingly, schema has been updated.
=> [enriched-jira] Track creator, assignee, reporter in issues

README.md
It seems we never update the link to GrimoireLab tutorial...
=> Fix outdated link to GrimoireLab tutorial

grimoire_elk/enriched/meetup.py, schema/meetup.csv, tests/test_meetup.py
This code stores the attribute `group_created` as date. Furthermore, corresponding tests and CSV have been updated accordingly.
=> [meetup] Store `group_created` as date

requirements.txt, setup.py
This change is needed to align the dep version of pandas to the one used in SortingHat. It address https://github.com/chaoss/grimoirelab-sortinghat/issues/209
=> [dependencies] Update pandas dependency to 0.22.0

grimoire_elk/enriched/mediawiki.py
This code removes the calls to add indentity and project information from the method `get_rich_item`. This code has no effect since it was already added in `get_rich_item_reviews`.
=> [enriched-mediawiki] Remove identity/project info in get_rich_item

grimoire_elk/enriched/git.py, tests/test_git.py
This code removes possible credentials declared on https URLs for Git repositories. This is the case of private repos on GitHub, which may be accessed by passing the username and token on the URL.
Tests have been provided accordingly.
=> [enriched-git] Remove credentials from Git URLs

grimoire_elk/raw/askbot.py, schema/askbot.csv, schema/bugzilla.csv, schema/confluence.csv, schema/crates.csv, schema/discourse.csv, schema/git.csv, schema/github_issues.csv, schema/irc.csv, schema/jira.csv, schema/kafka.csv, schema/maniphest.csv, schema/mbox.csv, schema/mediawiki.csv, schema/meetup.csv, schema/redmine.csv, schema/rss.csv, schema/stackoverflow.csv, tests/base.py, tests/model.py
This PR removes the reference to ocean-unique-id from ELK. This attribute was used before the introduction of the attribute `uuid` in Perceval items. Tests and the schemas below have been updated, furthermore the method `fix_item` from the raw connector of Askbot has been removed.
- askbot
- bugzilla
- confluence
- discourse
- git
- github_issues
- irc
- jira
- kafka
- maniphest
- mbox
- mediawiki
- meetup
- redmine
- rss
- stackoverflow
=> [ELK] Remove reference to ocean-unique-id info

grimoire_elk/enriched/study_ceres_aoc.py
This code includes the `origin` in the items generated by the AOC study. This change is needed to make the incrementality work in ceres, since it relies on this attribute (https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/ceres_base.py#L261)
=> [enriched-aoc] Include origin in AOC items

grimoire_elk/enriched/gerrit.py, tests/data/gerrit.json, tests/test_gerrit.py
This code handles missing user information (approvers, patchset and changeset authors) when calculating the time to first review for patchsets and changesets as well as the reviews' last status value.
In case the user information is missing, the aformentioned values are now calculated (before they were set to None).
=> [enriched-gerrit] Handle missing user information

grimoire_elk/raw/jenkins.py, tests/test_jenkins.py
This code allows to handle multiple parameters passed via the repo url, defined within the projects.json. This change is needed since the jenkins raw connector is redefining the method `get_p2o_params_from_url`, which contains the logic to handle `--filter`-like parameters.
=> [raw-jenkins] Handle multiple params on repo url

grimoire_elk/enriched/discourse.py
This code allows to handle missing author information such as `display_username` and `username`, which are set to None.
Related to https://github.com/chaoss/grimoirelab-elk/issues/701
=> [enriched-discourse] Handle missing author information

grimoire_elk/enriched/discourse.py, tests/data/discourse.json, tests/data/projects-release.json, tests/test_discourse.py
This PR fixes the tests concerning the enrichment phases for discourse items by replacing the current origin (which isn't accessible) with a new one. Furthermore, the method `__show_categories_tree` is removed since not reachable.
=> [discourse] Fix test and remove dead code

.travis.yml
This code extends the tests executed on ELK to python 3.5 and 3.6.
=> [travis] Support tests for python 3.5 and 3.6

grimoire_elk/enriched/enrich.py, tests/data/projects-release.json
This code fixes the way the projects map is built by processing the repositories under the `unknown`
section at the very end. This change is needed to avoid assigning repositories to the generic
project `Main` when they are also declared in other projects.
This error appears with Python 3.5, but not with Python 3.6 and it is related to how the dictionary
keys are ordered.
=> [enriched-enrich] Fix conversion projects.json to map

grimoire_elk/elastic_items.py
This code strips out white spaces of repo urls having the param `--labels` enabled. This fix is needed to correctly match the url when enriching raw data.
=> [elastic_items] Remove white spaces from repo url with labels

grimoire_elk/enriched/bugzillarest.py, tests/data/bugzillarest.json, tests/test_bugzillarest.py
This code handles missing user info such as email, name and username by replacing the latter with `None`.
Tests and the corresponding data have been added accordingly.
Fixes https://github.com/chaoss/grimoirelab-elk/issues/729
=> [enriched-bugzillarest] Handle missing user info

requirements.txt, setup.py
This code updates the dependecy for redis package, which is now pinned to 3.0.0
Related to https://github.com/chaoss/grimoirelab-elk/issues/726
=> [dependencies] Update redis to 3.0.0

grimoire_elk/enriched/meetup.py, schema/meetup.csv, tests/test_meetup.py
This code fixes a typo in the attribute containing the url name of a meetup group. The correct attribute is `urlname`.
Tests data and the corresponding tests have been modified accordingly.
Fixes https://github.com/chaoss/grimoirelab-elk/issues/725
=> [enriched-meetup] Fix typo in group url name

grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/jira.py, grimoire_elk/enriched/meetup.py
This code returns an empty item_sh when sortinghat isn't set.
This change is needed to allow ELK working without Sortinghat.
=> [enriched-enrich] Set empty item_sh when sortinghat is not set

grimoire_elk/enriched/gitlab.py, tests/data/gitlab.json, tests/test_gitlab.py
This code allows to prevent TypeError: 'NoneType' exception
when the issue or merge has no author data.
Signed-off-by: Quan Zhou <zhquan7@gmail.com>
=> [enrich-gitlab] Handle TypeError: 'NoneType' exception

grimoire_elk/elastic_items.py, grimoire_elk/utils.py, utils/p2o.py
Wait a configurable amount of time (in seconds) via `--scrol=wait`, for example `--scroll-wait 30` (default is 900)
Fixes #758 
Signed-off-by: Lukasz Gryglicki <lukaszgryglicki@o2.pl>
=> Add support for releasing scroll and waiting for available scroll, fixes #758

setup.py
If we pin pandas at 0.22.0, it doesn't build
with Python 3.7.x, apparently because of problems
when building numpy for pandas.
Letting pandas be greater or equal than 0.22.0
doesn't seem to break anything, since platforms
having only 0.22.0, as Travis had in July'19,
would still fulfill the dependency.
Signed-off-by: Jesus M. Gonzalez-Barahona <jgb@gsyc.es>
=> Let pandas be >= 0.22.0

grimoire_elk/elastic.py, grimoire_elk/errors.py, grimoire_elk/utils.py, tests/test_elk_elsticsearch.py, tests/test_errors.py, utils/gelk.py, utils/gh2arthur.py
This code models the errors coming from the Elastic class by defining the exception `ElasticError`. This new error replaces the exceptions ElasticConnectException and ElasticWriteException.
=> [elk] Replace ElasticConnect, ElasticWriter exceptions with ElasticError

grimoire_elk/elk.py, grimoire_elk/enriched/git.py, grimoire_elk/enriched/sortinghat_gelk.py
This code removes the support to include author and committer information extracted from github commits, when enriching git data. This feature isn't used, in its current state it won't work for github enterprise instances and it may slow down the enrichment of git data.
Related code present in elk.py and sortinghat_gelk.py has been removed accordingly.
Review together with: https://github.com/chaoss/grimoirelab-sirmordred/pull/390
Deprecates https://github.com/chaoss/grimoirelab-elk/pull/753
=> [git-enriched] Remove github commit support

grimoire_elk/enriched/dockerhub.py
This PR addresses https://github.com/chaoss/grimoirelab-elk/issues/767, thus it allows to ignore dockerhub images, which don't have a last updated value. This is the case of https://hub.docker.com/r/hyperledger/sawtooth-next-directory, that doesn't have any activity.
=> [enriched-dockerhub] Handle never updated images

grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/github.py, grimoire_elk/enriched/github2.py, requirements.txt, setup.py, tests/data/github.json, tests/data/github2.json, tests/test_github.py, tests/test_github2.py
This study includes geo points information (latitude and longitude) based on the value of the `location_field`. The coordinates are retrieved using Nominatim through the geopy package (which required to update the setup.py and requirements.txt), and saved in the `geolocation_field`.
All locations included in the `location_field` are retrieved from
the enriched index. For each location, the geo points are retrieved and saved
to the `geolocation_field`. In case the geo points are not retrieved,
the location is ignored.
The example below shows how to activate the study by modifying
the setup.cfg. The study `enrich_geolocation:user` retrieves location data
from `user_location` and stores the geo points to `user_geolocation`. In a
similar manner, `enrich_geolocation:assignee` takes the data …
=> [enriched-enrich] Add geolocation study

.travis.yml, requirements.txt
This code extends the CI tests to python 3.7. Furthermore, the pandas dependency in the requirements.txt is relaxed and aligned with the corresponding one in the setup.py.
=> Support python 3.7

grimoire_elk/enriched/gitlab.py, tests/data/gitlab.json, tests/test_gitlab.py
This code fixes the 'repository' value of the merge requests URL.
The api add the character '-' before '/merge_requests/'.
Tests data and the corresponding tests have been modified
accordingly.
Signed-off-by: Quan Zhou <zhquan7@gmail.com>
=> [enriched-gitlab] Fix repository value in merge

grimoire_elk/enriched/jira.py, tests/data/jira.json, tests/test_jira.py
This code allows to handle creators and assignees without displayName or name.
Tests data have been modified accordingly.
=> [enriched-jira] Handle missing creator/ assignee displayName and name

README.md
The last point in the [README.md#enriched-data](https://github.com/chaoss/grimoirelab-elk/blob/master/README.md#enriched-data) is Twitter.
```
Telegram: each document corresponds to a message.
Telegram: each document corresponds to a tweet.
```
This PR fixes it. :slightly_smiling_face:
=> [doc] fix mistake in README.md

README.md
This code enhances the README.md by adding the information to execute the tests. Furthermore details about how to use the coverage package are also included.
=> [doc] Add documentation to run tests and coverage

grimoire_elk/enriched/github.py, grimoire_elk/enriched/github_study_evolution.py, schema/github_backlog.csv, tests/test_github.py
This PR fix the issue https://github.com/chaoss/grimoirelab-elk/issues/761 to add additional index to compute
the chronological evolution of opened issues and average opened time 
issues.
For each repository and label, we start the study on repository
creation date until today with a day interval (default). For each date
we retrieve the number of open issue at this date by difference between
number of opened issues and number of closed issues. In addition, we
compute the average opened time for all issues open at this date.
To differenciate by label, we compute evolution for bugs and all others
labels (like "enhancement","good first issue" ... ), we call this
"reduced labels". We need to use theses reduced labels because the
complixity to compute evolution for each combinaison of labels …
=> [github] GitHub evolution backlog

grimoire_elk/enriched/github2.py
This code fixes the way the identities are loaded in the method `get_identities` to make the process
more efficient. The problem is that the loop that loads the identities found in comments is executed
for each identity type, however this loop should be executed just once.
The fix allows to execute the aforementioned just once.
=> [github2] Fix loading identities

schema/github_pull_requests.csv
This change updates the misleading description of the field `time_to_merge_request_response`
Signed-off-by: snack0verflow <f20160562@hyderabad.bits-pilani.ac.in>
=> [schema] Update field description

grimoire_elk/enriched/gitlab.py, tests/data/gitlab.json
This code fixes the 'repository' value of the issues URL.
The api add the character '-' before '/issues/'.
Tests data and the corresponding tests have been modified
accordingly.
=> [enriched-gitlab] Fix repository value in issue

grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py, grimoire_elk/enriched/github.py, grimoire_elk/enriched/gitlab.py, grimoire_elk/enriched/meetup.py, tests/test_git.py, tests/test_github.py, tests/test_gitlab.py, tests/test_meetup.py
This pull request includes the fields related to Sortinghat with reasonable data when it is disabled:
- id, gender, gender_acc, org_name and bot are empty.
- name, username and domain are obtained from the identity.
- uuid is calculated with a hash of the backend, name, email and username using the function provided by sortinghat
=> [sortinghat] Create enriched fields related to Sortinghat when it is disabled

schema/askbot.csv
This PR updates the askbot schema to the latest format.
Reference to #803
=> [schema] Update askbot.csv

schema/dockerhub.csv
This PR updates the dockerhub schema to the latest format.
Reference to #803
=> [schema] Update dockerhub.csv

grimoire_elk/enriched/meetup.py, releases/unreleased/fix-missing-geolocation-in-meetup-event.yml, tests/data/meetup.json, tests/test_meetup.py
This code handles the meetup events for which the geolocation isn't provided. Thus, for these events the venue_geolocation is set to None.
Fixes #826
=> [enriched-meetup] Handle event without geolocation

tests/base.py
Noticed that many of the tests did not work completely because of missing projects json mapping. Added the line to use projects map from SQL database `test_projects.sql` ,observed increase in test coverage.
Signed-off-by: Nitish Gupta <imnitish.ng@gmail.com>
=> added projects_map db to improve coverage

grimoire_elk/enriched/cocom.py, releases/unreleased/code-complexity-per-language.yml
This PR fix issues https://github.com/chaoss/grimoirelab-elk/issues/782 and https://github.com/chaoss/grimoirelab-elk/issues/783
The field `language`  is add to cocom study index. A dict to associate the extension to a language is used. If the extension is not found, we considere the extension in upper case as the language name. 
Currently, the study compute the total for several metrics. But we cannot differenciate this total per the source code language. In this PR we propose to compute this metrics for each language. The sum of value for each language is equal to the old total value.
=> [cocom] total per language

tests/base.py
Change logic to delete all the test indexes created during a test, rather than just the `raw` and `enriched` index.
Fixes https://github.com/chaoss/grimoirelab-elk/issues/837
Signed-off-by: Nitish Gupta <imnitish.ng@gmail.com>
=> changed logic to delete all test indexes

grimoire_elk/enriched/bugzillarest.py, schema/bugzilla.csv, tests/test_bugzillarest.py
This code add the field `is_open` to know if the tiket is open.
=> [enriched-bugzillarest] Add new field `is_open`

tests/test_githubql.py, tests/test_gitlab.py, tests/test_gitter.py
This commit adds the test to check if perceval
params are correctly initiatized. The test was
missing in Gitter, GitLab and GithubQl backends
and thus has been added.
Signed-off-by: Animesh Kumar <animuz111@gmail.com>
=> [test] Add missing test for perceval params

grimoire_elk/enriched/slack.py, schema/slack.csv, tests/data/slack.json, tests/test_slack.py
Fixes: #867 
This commit removes enriching single files,
since a message can contain multiple files.
Instead, two new metrics, number of files and
file size per message have been included.
The schema has been updated.
The tests have been updated accordingly.
Signed-off-by: Animesh Kumar <animuz111@gmail.com>
=> [slack] Update files metric

grimoire_elk/enriched/gerrit.py, schema/gerrit.csv, tests/test_gerrit.py
This code copies the attributes `status` and `status_value` of the changeset to the corresponding patchsets. With these new attributes, it is possible to compare the time to first review for patchsets belonging to a given type of changesets (e.g.,
merged, abandoned or new).
These new attributes are also included in the changeset enriched items for consistency purpose.
Tests have been updated accordingly.
Schema has been updated accordingly.
=> [enriched-gerrit] Propagate changeset status to patchsets

grimoire_elk/elk.py, grimoire_elk/enriched/crates.py, grimoire_elk/enriched/jenkins.py, grimoire_elk/enriched/kitsune.py, grimoire_elk/enriched/mbox.py, grimoire_elk/enriched/mbox_study_kip.py, grimoire_elk/enriched/puppetforge.py, grimoire_elk/enriched/rss.py, grimoire_elk/enriched/supybot.py, grimoire_elk/enriched/twitter.py, grimoire_elk/enriched/utils.py, grimoire_elk/utils.py
This code replaces the calls to the datetime and dateutil calls to the equivalent ones provided by toolkit. This is needed to centralize the possible point of failures to a single library.
=> [grimoire_elk] Replace datetime/dateutil calls with toolkit

grimoire_elk/enriched/mbox_study_kip.py
This code fixes the way the attributes kip_discuss_inactive_days and kip_voting_inactive_days are calculated by not removing the tzinfo information. This change is needed since the function
`get_time_diff_days` needs both dates to be offset-aware.
=> [enriched-mbox-study-kip] Fix calculation for inactive days

grimoire_elk/utils.py
This code removes the function `get_time_diff_days`, which isn't used in the codebase.
=> [utils] Remove unused function get_time_diff_days

grimoire_elk/elastic.py, grimoire_elk/elastic_items.py, grimoire_elk/elk.py, grimoire_elk/enriched/cocom.py, grimoire_elk/enriched/colic.py, grimoire_elk/enriched/dockerhub.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py, grimoire_elk/enriched/github.py, grimoire_elk/enriched/graal_study_evolution.py, grimoire_elk/enriched/jira.py, grimoire_elk/enriched/kitsune.py, grimoire_elk/enriched/mbox.py, grimoire_elk/enriched/mbox_study_kip.py, grimoire_elk/enriched/mediawiki.py, grimoire_elk/enriched/mozillaclub.py, grimoire_elk/enriched/utils.py, grimoire_elk/raw/elastic.py, grimoire_elk/raw/git.py, releases/unreleased/support-for-git-private-repos.yml, tests/base.py, tests/data/git.json, tests/test_elastic.py, tests/test_enrich.py, tests/test_gerrit.py, tests/test_git.py, tests/test_github.py, tests/test_github2.py
This code allows to handle Git private repos, which credentials are passed via the projects.json. To achieve this, the method `anonymize_url` in grimoire_elk/elastic.py has been removed and an equivalent function has been added to enriched/utils. This change is needed to ease the use of the
anonymize url feature across ELK.
The Git raw connector has been modified to include the method `_fix_item`, which takes care of removing the credentials that may appear in the origin. This change is needed to prevent storing in the raw index the credentials to access the Git private repos.
The method `get_repository_filter` in the enriched/utils has been modified to omit the credentials that may appear on the repo origin when creating the filter to get the data from the corresponding
raw index.
The …
=> Handle Git private repos in ELK

grimoire_elk/enriched/git.py, releases/unreleased/sync-aoc-and-git-indexes.yml
This code allows to delete the documents corresponding to commits that don't exist anymore in upstream. This is achieved by calculating the difference between the commit hashes in the AOC and raw indexes, the obtained hashes are deleted from the AOC index.
This approach is similar to the one implemented in the method `update_items`, which allows to sync the Git raw and enriched indexes with the local clone.
This PR also extends the support for private git repositories when deleting commits from the git indexes (raw, enrich and aoc).
=> [enriched-git] Sync AOC and Git raw index

grimoire_elk/enriched/mediawiki.py, grimoire_elk/raw/elastic.py, tests/data/mediawiki.json, tests/data/projects-release.json, tests/test_mediawiki.py
This code allows to support the filter no-collection for URLs composed of multiples params, for instance:
```
"https://wiki-archive.opendaylight.org https://wiki-archive.opendaylight.org/view"
```
=> [elastic] Support for filter no-collection on multi params URLs

grimoire_elk/enriched/githubql.py
This code adds the attribute `label` which contains the issue labels to the closed events. This change is needed to allow calculations between label-related and closed events using a common attribute.
=> [enriched-githubql] Add label attribute to closed events

requirements.txt, setup.py
The numpy dependency is constrained to <= 1.18.3. This change is needed since from version 1.19.x the support for python 3.5 has been discontinued.
Refs:
- https://numpy.org/devdocs/release/1.19.0-notes.html#id1
- https://github.com/numpy/numpy/issues/16294
=> [deps] Constrain numpy version to <= 1.18.3

grimoire_elk/elk.py, grimoire_elk/enriched/utils.py
This code removes the tzinfo used to compare the `from_date` value with the default one (1970-01-01) to perform the incremental fetching.
This change is needed to fix a bug introduced at:
- https://github.com/chaoss/grimoirelab-elk/commit/e2994480c6e4c40c7736f911e4287660e2863f31#diff-a94b51d8c8a4c2e33e52cff8968a0b3cR158
- https://github.com/chaoss/grimoirelab-elk/commit/e2994480c6e4c40c7736f911e4287660e2863f31#diff-928a29f9b639dcb91b5081e292e0d1c3R170
The bug consists in not removing the tzinfo from the value obtained from the method `str_to_datetime`.
=> [grimoire_elk] Remove tzinfo for date comparison

grimoire_elk/enriched/slack.py, tests/data/slack.json, tests/test_slack.py
This code allows to handle the rare cases where neither the user data nor bot ID are present in
the Perceval document. For these cases, an empty identity is returned by the method `get_sh_identity`.
Related to https://github.com/chaoss/grimoirelab-perceval/pull/675
=> [enriched-slack] Handle messages without user data/bot ID

grimoire_elk/enriched/githubql.py
This code allows to tune from the setup.cfg the number of events without duration attribute returned per page. This change is useful to adapt the resources used by this study to the enviroment where GrimoireLab is running.
=> [enriched-githubql] Add page size param to duration study

grimoire_elk/enriched/git.py
This code prevents to delete commits from the raw and enriched indexes when no commits are returned from the local Git repository. This change is needed to cover the cases when an error is thrown during the execution of `rev_list` or when the location of the local repo has changed.
=> [enriched-git] Execute update_items when local repo commits are returned

grimoire_elk/enriched/enrich.py, requirements.txt, setup.py
This code sets the user-agent used by the study enrich_geolocation. This change is needed to support
geopy 2.0.0, which requires the declaration of a custom user-agent.
=> [enriched-enrich] Set user-agent for geopy

grimoire_elk/enriched/mediawiki.py, tests/test_mediawiki.py
This code adds the `repository_labels` field to the enriched index.
Test updated accordingly.
=> [enriched/mediawiki] Add `repository_labels` field

grimoire_elk/enriched/git.py, tests/test_git.py
This code allows to execute the study AOC when the repo contains
extra fields like `--lables=[]`.
=> [enriched/git] Study aoc support extra fields

grimoire_elk/enriched/jira.py, tests/test_jira.py
These fields allow us to know if the issue is closed or open:
- `is_closed`: 1 if the issue is closed or 0 if not.
- `status_category_key`: The key of the issue status.
=> [enriched/jira] Add `is_closed` and `status_category_key` fields

grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/gerrit.py, schema/demography_contribution.csv, schema/gerrit.csv, tests/test_gerrit.py
This new study creates new fields to give us the first and last
date of different contribution types for each author.
i.e. of the new fields:
- approval_min_date, approval_max_date
- changeset_min_date, changeset_max_date
- comment_min_date, comment_max_date
- patchset_min_date, patchset_max_date
Schema updated accordingly.
=> [enriched/gerrit] Add new study 'enrich_demography_contribution'

grimoire_elk/enriched/githubql.py, schema/cross_references.csv, schema/github_events.csv, tests/test_githubql.py
The purpose of this study is to gather all the issues and pull requests which are mutually referenced.
Once these references are obtained, all of the events for the given issue or pull request are updated with the corresponding list of URLs from the referenced items.
The following fields are added:
* `referenced_by_issues`: List of issues referenced by a given Issue or Pull Request, from the same repository.
* `referenced_by_prs`: List of pull requests referenced by a given Issue or Pull Request, from the same repository.
* `referenced_by_external_issues`: List of issues referenced by a given Issue or Pull Request, from different (external) repositories.
* `referenced_by_external_prs`: List of pull requests referenced by a given Issue or Pull Request, from different (external) …
=> [enriched/githubql] Add new study 'enrich_reference_analysis'

grimoire_elk/enriched/weblate.py, grimoire_elk/raw/weblate.py, grimoire_elk/utils.py, requirements.txt, tests/data/projects-release.json, tests/data/weblate.json, tests/test_weblate.py
This code proposes a new weblate enricher to handle changes
including their units and author information.
Demography study included.
The new enricher is added to the list of connetors and can be
defined in the mordred setup.cfg as follows:
```
[weblate]
raw_index = weblate_chaoss_raw
enriched_index = weblate_chaoss_enriched
api-token= ...
no-archive = true
sleep-for-rate = true
studies = [enrich_demography:weblate]
[enrich_demography:weblate]
```
projects.json
```
{
"chaoss": {
"weblate": [
"my.weblate.org"
]
}
}
```
Tests added accordingly.
=> [weblate] New enricher to handle changes

grimoire_elk/enriched/githubql.py, schema/cross_references.csv, tests/data/githubql.json, tests/test_githubql.py
The cross reference study now classifies merged GitHub PRs based on a list obtained from `MergedEvents` items. These merged PRs are divided in the following two new fields:
* `referenced_by_merged_prs`: Referenced, merged PRs from the same repository as the issue or PR referencing it.
* `referenced_by_external_merged_prs`: Referenced, merged PRs from a different repository of the one from the issue or referencing it.
These new fields are also updated for the rest of GitHub-related indexes for all the affected elements identified by `issue_url`.
Note: I'm preparing another PR to `grimoirelab-sigils` repository to update `githubql` and the rest of github-related index patterns with new fields. **EDIT**: PR available at https://github.com/chaoss/grimoirelab-sigils/pull/480.
=> [enriched/githubql] Classify merged PRs within cross-references study

grimoire_elk/enriched/github.py, schema/github_pull_requests.csv, tests/test_github.py
The new fields added to the enricher are the number of additions, deletions and changed files in a GitHub Pull Request.
The related schema file has been updated with these three new fields.
**Note**: This PR is related to another related PR updating the `github_issues` index pattern with these new fields (https://github.com/chaoss/grimoirelab-sigils/pull/482).
=> [enriched/github:prs] Add fields for Pull Requests-related data

grimoire_elk/enriched/stackexchange.py
This code allows to deal with deleted users in answers in StackOverflow, logging a warning.
The implementation for this PR is similar to the code used to handle deleted users in questions.
One example of an answer without owner is https://stackoverflow.com/a/339388/15335404
=> [enrich-stackexchange] Handle deleted user in stackoverflow

grimoire_elk/identities/git.py, grimoire_elk/identities/github.py, grimoire_elk/identities/identities.py, grimoire_elk/identities/meetup.py, grimoire_elk/identities/stackexchange.py, grimoire_elk/raw/stackexchange.py, tests/test_stackexchange.py
This code makes it optional to pseudo-anonymize the owner of question and answers. It creates a hash of the name and user_id and remove author_link and profile_image.
For enabling the anonymization, include the following parameter in the stackexchange section:
```
[stackexchange]
...
anonymize = true
```
=> [stackexchange] Make author anonymization optional for stackexchange

grimoire_elk/enriched/twitter.py
The data returned from Twitter has deprecated fields that are set to null. We can remove these fields from the enriched twitter object since they are always going to be returned as null and are not going to be of much use. You can cross-check the deprecated fields [here.](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/user)
=> [enriched/twitter] Remove deprecated attributes from enriched item

tests/test_phabricator.py
test_phabricator was missing coverage for line 85. This commit adds the test for that line.
Signed-off-by: sevagenv <sevagenv@gmail.com>
=> [tests] Add test for transactionID field

README.md
`Bugzilla` and `Bugzillarest`refers to the backends/APIs that is used in retrieving the data.
This commit rewords their description to denote the differences between the structure of both data and how they're obtained.
References: #972
Signed-off-by: stevekola <kolawolesteven99@gmail.com>
=> Reword Bugzilla's and Bugzillarest's descriptions

README.md
The README file has been updated with a brief description about the `Database` section from the `tests.conf` file and when it
should be included.
The base version for this `tests.conf` file has been updated with this section but with the new lines commented.
=> [README] Update instructions for running tests

grimoire_elk/enriched/github2.py, tests/data/github2.json, tests/test_github2.py
This code takes into account the deleted (ghost) users to
calculate the first attention and the first response. Also, fix
the `TypeError: 'NoneType'` error when the attention was made by
the ghost user.
=> [enriched/github2] Add ghost user to calculate first attention

grimoire_elk/enriched/enrich.py
This code adds `unaffiliated_group` to enrolls when it is empty
to fix the `IndexError`.
=> [enrich] Fix IndexError when getting main organization

grimoire_elk/enriched/enrich.py
This code fixes the SSLError when running the `enrich_feelings`
study available for github2.
The error:
```
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
```
=> [enrich] Fix urllib3.exceptions.SSLError for 'enrich_feelings'.

grimoire_elk/enriched/enrich.py, tests/test_enrich.py
This adds the `remove_prefix_enrollments` method to remove the
prefix when the organization name contains `::` for
`*_multi_org_names` fields.
=> [enrich] Remove the prefix '::' of the enrollments.

grimoire_elk/enriched/git.py, releases/unreleased/git-fix-'is_git_commit_multi_author'.yml
This fixes the `is_git_commit_multi_author` field when the
commit has more than one author and `pair-programming` is enabled.
This is important for calculating `pair_programming_*` values.
Also, set `git_uuid` correctly.
=> [enriched/git] Fix 'is_git_commit_multi_author' field.

grimoire_elk/raw/confluence.py, releases/unreleased/remove-confluence-credentials.yml, tests/data/confluence_with_credentials.json, tests/test_confluence.py
This code redefines the method _fix_item for the confluence raw
data in order to remove credentials that may appear in the origin,
tag and data.content_url fields.
This change is needed to prevent storing the credentials in the
raw index.
=> [raw/confluence] Remove credentials from raw items

grimoire_elk/elk.py, releases/unreleased/skip-sources-with-wrong-arguments.yml, tests/test_elk.py
When the source has a wrong argument, the current behavior is that
the process stops without any error messages.
This code will write an error message with the arguments
(anonymized) and skip the source so as not to stop the process.
=> [elk] Skip sources with wrong arguments

pyproject.toml, releases/unreleased/poetry-build-version-updated.yml
The current version of the poetry builder was old and caused some problems when installing packages in developer mode. With this new version, it's possible to install ELK in developer or editable mode without using setuptools files (i.e. `setup.cfg` and `setup.py`).
=> Update poetry builder version

grimoire_elk/raw/slack.py, releases/unreleased/[slack]-handle-fields-in-data.file.yml
This code allows handling the fields in `data.file` to
avoid the error `Failed to insert data to ES`
=> [raw/slack] Handle fields in 'data.file'

grimoire_elk/enriched/git.py, releases/unreleased/git-branches-study-skip-uncloned-repo.yml, tests/test_git.py
This code skips uncloned repositories and continues with the next
repository.
=> [git] Skip uncloned repositories for git-branches study

pyproject.toml
This commit fixes the 'include' list. It was a mix of dictionaries and strings.
=> [pyproject] Fix pyproject syntax

grimoire_elk/elk.py, grimoire_elk/enriched/cocom.py, grimoire_elk/enriched/colic.py, grimoire_elk/enriched/discourse.py, grimoire_elk/enriched/dockerdeps.py, grimoire_elk/enriched/dockersmells.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/gerrit.py, grimoire_elk/enriched/git.py, grimoire_elk/enriched/github.py, grimoire_elk/enriched/github2.py, grimoire_elk/enriched/githubql.py, grimoire_elk/enriched/gitlab.py, grimoire_elk/enriched/gitter.py, grimoire_elk/enriched/jenkins.py, grimoire_elk/enriched/launchpad.py, grimoire_elk/enriched/mattermost.py, grimoire_elk/enriched/mbox.py, grimoire_elk/enriched/pagure.py, grimoire_elk/enriched/phabricator.py, grimoire_elk/enriched/remo.py, grimoire_elk/enriched/weblate.py, tests/base.py, tests/test_sortinghat_gelk.py
This PR includes a new method in the enrichment process to verify the connection to the SortingHat database when using SSL.
This PR depends on https://github.com/chaoss/grimoirelab-sortinghat/pull/737
=> [sortinghat] Include db_verify_ssl option for SortingHat

grimoire_elk/enriched/enrich.py, releases/unreleased/fix-typo-in-is_bot-field.yml, tests/test_enrich.py
This PR updates the name of the fields that are obtained from the SortingHat API. Previously the fields were `gender_acc` and `is_bot` but now are `genderAcc` and `isBot`.
Update tests accordingly.
=> Fix typo in SortingHat API fields

grimoire_elk/elk.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py, grimoire_elk/enriched/sortinghat_gelk.py, releases/unreleased/enrichment-process-performance-improved.yml
This commit improves the performance of the enrichment process.
- Reduce the number of requests to get the backend name (`_connecto_name`).
- Reduce the number of queries to get information from SortingHat.
- Removes an unused method called `get_uuid`.
- Refactor and rename the `__fix_field_date` method to `__cast_str_to_datetime` to convert str to datetime and fix possible date format errors. With this method we reduce the number of calls of the `str_to_datetime` method.
- In the `__add_commit_meta_fields` method it only creates a new identity when it doesn't exist in SortingHat.
- In the `add_identity` method, remove the `update_profile` mutation; this is no longer necessary as we are using GraphQL.
=> Improve enrichment process performance

grimoire_elk/enriched/enrich.py, releases/unreleased/datetime-format-fixed-in-the-enrichment-process.yml, tests/test_git.py
This commit fixes the date format when there are several enrollments in profiles. Since the number of times the `str_to_datetime` method is executed has been reduced to improve performance the `date` field in `get_item_sh_from_id` and `get_item_sh_meta_fields` must be strings.
Test to enrich a profile with multiple enrollments added.
=> [enrich] Fix enrich items with multiple enrollments

grimoire_elk/enriched/bugzilla.py, releases/unreleased/bug-description-in-bugzilla.yml, schema/bugzilla.csv, tests/test_bugzilla.py
Include the description of the bugs in Bugzilla. The new fields are 'description' and 'description_analyzed'. The second allows to query any of the words of the description.
=> [bugzilla] Include bug description in Bugzilla enriched

grimoire_elk/enriched/github2.py, releases/unreleased/undefined-identities-in-github-comments.yml
This PR fixes a bug that cause that some identities were not loaded in SortingHat and in OpenSearch were displayed as UNDEFINED.
The method `get_identities` was not returning the identities from `reviews_data`.
=> [github] Fix get_identities method not returning all identities

grimoire_elk/enriched/enrich.py, releases/unreleased/error-in-opensearch-response-stops-demography-study.yml
Fix an issue that stops the demography study when OpenSearch occasionally provides a response without some expected fields.
=> [demography] Error in OpenSearch response stops demography study

grimoire_elk/enriched/enrich.py, releases/unreleased/field-author_uuid-incorrectly-assigned.yml
Correct a bug that results in enriched items using the individual ID as the identity ID, and vice versa.
This way:
- `author_uuid` = `individual.mk`
- `author_id` = `indentity.uuid`
=> Individual id incorrectly assigned to identity id

grimoire_elk/elk.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py, grimoire_elk/enriched/github2.py, releases/unreleased/sortinghat-backend-name-per-data-source.yml, tests/test_load_identities.py
This PR allows to change the backend name for SortingHat identities. The GitHub2 backend is updated from 'github2' to 'github'. This way GitHub2 and GitHub share the same identity in SortingHat.
This change could break existing dashboards because the new github comments ids will be different from the old ones.
=> Define the backend name for SortingHat identities

tests/test_elk.py
The Jira backend now has `--api-token` param and the test to check wrong params is broken. Change the parameter `--api-token` with something unexpected like `--foo-bar`.
=> [tests] Fix wrong params test

.github/workflows/release.yml
Prior to running SortingHat, it's important to install the package. This change ensures that we can utilize the identical version from the package when deploying SortingHat.
=> [ci/release] Install package before running SortingHat

grimoire_elk/enriched/jira.py, grimoire_elk/enriched/mediawiki.py, grimoire_elk/enriched/meetup.py, releases/unreleased/bug-on-some-backends-enrichment.yml
Mediawiki, Meetup are Jira were failing to retrieve the enrollment for an identity. Because the date was not a string.
=> [bug] Incorrect date type in identity enrollment retrieval

grimoire_elk/raw/kitsune.py, releases/unreleased/kitsune-raw-mapping-updated.yml
This PR includes the mapping for Kitsune to fix an error in inserting Perceval items when the field 'data.metadata.value' is too big.
=> [raw/kitsune] Include mapping for data.metadata.value too big

grimoire_elk/enriched/kitsune.py, releases/unreleased/kitsune-demography-study.yml, tests/test_kitsune.py
This PR allows to execute the demography study for Kitsune backend.
The enriched index now includes a unique identifier for questions and answers (`id`), this was causing an error when trying to autorefresh because `uuid` was missing.
Include the default raw fields in `answers` items that were missing: `metadata__updated_on` , `metadata__timestamp`, `offset`, `origin`, `tag`, and `uuid`.
=> [kitsune] Update enriched fields

grimoire_elk/raw/kitsune.py, releases/unreleased/kitsune-inmerse-terms-error.yml
This code modifies the raw mapping of Kitsune indexes to handle immense terms found in `data.answers_data.content`, and `data.content`. Thus, the corresponding field is converted to text.
=> [kitsune] Handle immense terms for Kitsune

grimoire_elk/raw/mbox.py, releases/unreleased/mbox-origin-url-anonymized.yml
This code redefines the method `_fix_item` for the MBOX raw data to remove credentials that may appear in the origin.
=> [MBOX] Remove credentials from origin and tag

.github/workflows/release.yml, .github/workflows/tests.yml
This commit updates the version of the database for SortingHat. Now SortingHat requires Mariadb 10.4 or higher and MySQL 8.1 or higher.
=> [CI] Update mariadb version

grimoire_elk/enriched/kitsune.py, releases/unreleased/kitsune-fields-updated.yml
Include new fields in Kitsune backend enriched index. Include `product` and `url` fields in answers, and 
`is_kitsune_question_solved`, `time_to_first_reply` and `url` in questions.
Closes https://github.com/chaoss/grimoirelab-elk/issues/1144, https://github.com/chaoss/grimoirelab-elk/issues/1145, https://github.com/chaoss/grimoirelab-elk/issues/1146, https://github.com/chaoss/grimoirelab-elk/issues/1147
=> [kitsune] Include new fields for Kitsune backend

grimoire_elk/raw/kitsune.py, releases/unreleased/kitsune-mapping-updated.yml
This PR updates the mapping for the raw index of Kitsune. It was not including all the fields because dynamic was set to false in the data attribute.
=> Update Kitsune raw mapping

grimoire_elk/enriched/git.py, releases/unreleased/git-branches-study-fixed.yml
This PR fixes the Git branches study. There was a bug that didn't reset the list of commits assigned to branches, causing commits to be assigned to the wrong branches.
=> [git] Fix branches study that assigns wrong branches to commits

grimoire_elk/raw/github.py, releases/unreleased/github-url-ending-with-slash-failed.yml, tests/test_github.py
This commit fixes a bug that causes GrimoireLab to fail running GitHub URLs ending in a slash.
Fixes https://github.com/chaoss/grimoirelab-elk/issues/1159
=> [github] Fix GitHub failing with URL ending with a slash

grimoire_elk/elk.py, releases/unreleased/identity-refresh-bug-for-some-items.yml
This PR updates the filter construction to correctly match UUIDs in OpenSearch, addressing a bug in Mordred that prevented role identities from being refreshed.
This PR with https://github.com/chaoss/grimoirelab-sirmordred/pull/626 fixes https://github.com/chaoss/grimoirelab-elk/issues/1161
=> Update the author's filter in autorefresh process

grimoire_elk/enriched/enrich.py, releases/unreleased/roles-attribute-not-available-on-some-enrichers.yml
The 'roles' attribute wasn't available for all the enrichers. The attribute has been added to the main class 'Enrich' so subclasses will have it available even when they don't use it.
=> [enrich] Fix 'roles' attribute error

grimoire_elk/enriched/git.py, releases/unreleased/git-branches-study-improved.yml
Previously, while the branches study was running, the `branches` field remained empty or partially filled until the study was completed, leading to incorrect data being displayed on the dashboard.
With this change, the study is first created in an auxiliary field `branches_aux`, and once complete, the results are moved to the `branches` field.
=> [git] Improve branches study for consistency

grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/sortinghat_gelk.py, releases/unreleased/avoid-undefined-values-in-author-fields.yml, tests/test_git.py, tests/test_github.py, tests/test_gitlab.py
Avoid `-- UNDEFINED --` values for all SortingHat fields when
Mordred loses connection to the SortingHat server during the
enrichment or autorefresh execution. It will keep the values
​of the `name`, `email`, `id` and `uuid` fields.
=> [enrich] Avoid "-- UNDEFINED --" values

.github/workflows/release.yml, .github/workflows/tests.yml, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/functest.py, grimoire_elk/enriched/github.py, poetry.lock, pyproject.toml, releases/unreleased/python-minimum-version-updated.yml
Python 3.8 will reach its end of life in October 2024, and Python 3.9 will become the minimum version required by the project.
Update the GitHub workflows to run tests for Python 3.9, 3.10 and 3.11 for future releases.
Update some pinned dependencies due to old errors that seem to have been fixed.
Related to https://github.com/chaoss/grimoirelab/issues/699
=> Drop Python 3.8 support

grimoire_elk/enriched/bugzilla.py, grimoire_elk/enriched/bugzillarest.py, releases/unreleased/new-reponse-times-on-bugzilla-items.yml, schema/bugzilla.csv, tests/data/bugzilla.json, tests/test_bugzilla.py, tests/test_bugzillarest.py
The Bugzilla enriched items include two new fields to track response times on these type of repositories:
- `time_to_first_attention` is the the time expressed in days between the ticket creation and the first comment from a contributor different from the author creating the bug.
- `last_comment_date` is the date of the last comment posted in the bug.
=> Add reponse times for bugzilla indices

grimoire_elk/enriched/githubql.py, releases/unreleased/the-enrich_reference_analysis-study-process-all-references.yml
This code fixes the `enrich_reference_analysis` study that only processed the first 10 references instead of all of them. By default, the ElasticSearch/OpenSearch `aggregations` query only returns the first 10 documents. Using `composite aggregations` we can paginate the result to get all the references.
Fixes #1172
=> [enriched/githubql] Fix enrich_reference_analysis study

schema/bugzilla.csv
The CSV now includes descriptions for all the fields from the Bugzilla backend (some of them also come from the Bugzillarest backend).
=> Update schema for Bugzilla enriched data with field descriptions

.github/workflows/release.yml, .github/workflows/tests.yml
This PR adds Python 3.12 tests to the GitHub Actions workflows. These tests were missing during the migration from 3.8 to 3.9 due to incompatibilities with NumPy and the available packages at that time
=> Include Python 3.12 in workflow tests

.github/workflows/changelog.yml, .github/workflows/release.yml, README.md, doc/studies.md
Update files to support the migration of GrimoireLab repositories as part of the default branch transition from master to main.
=> Migrate files for branch rename from master to main

grimoire_elk/elk.py, releases/unreleased/github-incremental-collection-date-defaults.yml
This PR fixes an issue that stopped GitHub from collecting issues incrementally. The comparison for `from_date` was being made against the date `1970-01-01` instead of using the backend's default `from_date`.
=> Use Perceval backend-specific from_date as default value

grimoire_elk/enriched/utils.py, releases/unreleased/incorrect-from-date-behavior-for-enrich-tasks.yml
Remove enriching behavior using `from-date` parameter because it should only apply to collection, not enriching.
There was a bug where `from-date` was being compared against `1970-01-01`, which is incorrect since each backend has its own default `from-date`. This caused enrich tasks to enrich all items based on a shared default value instead of their backend-specific value.
Additionally, using `from-date` value from configuration was causing items collected after that date to be enriched, rather than enriching only the items that were updated in the origin data source since that date.
Removing that code fixes an issue that was causing all items from GitHub to be enriched instead of enriching only those items that are inserted after `metadata__timestamp`.
=> Fix incorrect from-date enriching behavior

grimoire_elk/enriched/github.py, releases/unreleased/github-assignee-keyerror-in-enriched-index.yml
This commit fixes the `KeyError` when the issue was assigned to a deleted user.
A deleted user does not have these fields:
- email
- company
- location
=> [enriched/github] Fix assignee fields

grimoire_elk/enriched/github.py, grimoire_elk/enriched/github2.py, releases/unreleased/github-keyerror-in-enriched-index.yml
This commit fixes the `KeyError` when the issue and/or pull request was assigned to `Copilot` user.
The `Copilot` user does not have thise fields:
- email
- company
- location
=> [enriched/github] Fix KeyError

.github/workflows/release.yml, .github/workflows/tests.yml, grimoire_elk/elk.py, grimoire_elk/enriched/ceres_base.py, grimoire_elk/enriched/cocom.py, grimoire_elk/enriched/colic.py, grimoire_elk/enriched/enrich.py, grimoire_elk/enriched/git.py, grimoire_elk/enriched/github.py, grimoire_elk/enriched/githubql.py, grimoire_elk/enriched/study_ceres_aoc.py, grimoire_elk/enriched/study_ceres_onion.py, grimoire_elk/utils.py, poetry.lock, pyproject.toml, releases/unreleased/elasticsearch-6-is-not-supported.yml, releases/unreleased/increased-minimum-version-for-python-to-310.yml, tests/base.py
Update workflows and configuration to support Python 3.10.
Python 3.9 will no longer receive updates after October 2025. This change ensures compatibility with newer features and maintains security for the project.
Remove `elasticsearch` package and use the latest version of `opensearch-py` for future development. This change makes that ElasticSearch 6 is no longer compatible.
=> Drop Python 3.9 and ElasticSearch 6 support

.github/workflows/release.yml, .github/workflows/tests.yml
This PR removes Python 3.13 from the tests and release workflows to prevent creating a large number of jobs for each test.
=> Reduce the number of jobs in workflows
